### ISSUE TITLE
Missing assignments for Settings Catalog policies when using the dokumentation feature 

### ISSUE THREAD

**Issue by dotjesper** [Micke-K/IntuneManagement#102]
Hi Micke,
I am back, have been extremely busy, new job and new challenges and more :)

I am using your solution all the time and is impressed with the continued evolvement of the solution. Hoverer, I seem to have found a small bug, as assignments for Settings Catalog policies doesn't show in the output when using the Document functionality. As far as I can conclude, this behavior is on Settings Catalog policies only.

Is this expected behavior or I am missing some setting somewhere?

Thanks
--Jesper

**Comment by dotjesper** [comment]
Quick update, I have tested the purposed script in [Discussion 103](https://github.com/Micke-K/IntuneManagement/issues/103) and the assignment reporting is working with Settings Catalog polices.

I hereby open another idea, I would be happy to create a separate Feature Request for it, but just want to send up a weather balloon. Have you considered adding an option for the dokumentation feature, allowing me to choose whatever Assignments should be part of the export or not. I am building a policy framework to share here at GitHub, and wanted to be able to document the policies without the assignment :)

Another add-on, would be, to be able to document selected policies, however with one mark-down file pr. policy, is that even possible?

Thank you for all your great work.

**Comment by dotjesper** [comment]
I have tested/used the new module and it looks quite good.

Is there any way to exclude the Style from the Markdown report?
Pointing to an empty style file, seems  to do the trick.

There is multiple levels of "Device configuration" is this by purpose?
![image](https://user-images.githubusercontent.com/6966543/209788256-1ef10fe3-23e8-4a9f-b1be-aa1089b1d0ab.png)

Thanks

**Comment by Micke-K** [comment]
Hello!

What MD viewer do you use? I thought it looked quite boring in Edge without the styles. I could probably add a checkbox to apply it or not. 

The two "Device configuration" in ToC looks weird but I don't remember what it was supposed to be :). Is it the same in HTML output?

I'm celebrating Christmas and New Year in Sweden at the moment so I have limited time to fix this now. 

Cheers!

**Comment by Micke-K** [comment]
Hello

Fixed included in 3.8.1

Let me know if there is anything else on this or if I can close the issue

Cheers!

**Comment by Micke-K** [comment]
Hello,

Closing issue as a fix was implement in a release.

Cheers
