### ISSUE TITLE
Feature Request: Export of health scripts

### ISSUE THREAD

**Issue by dotjesper** [Micke-K/IntuneManagement#103]
Hi,

Have you had considerations regarding exporting/saving (converting) the scripts from health scripts as an option as experienced when exporting PowerShell scripts. I am aware users can gain access to the script from within the console, or by converting the base64 string from the exported json, just for pure convenience :)

Thanks
--Jesper

**Comment by Micke-K** [comment]
Hello,

Can you try this. I've added export of scripts for Health Scripts and Win32 Apps (Detect- and Requirement rules)
This also has includes support for Reusable Groups (eg Endpoint Security Firewall rules)

And it should also fix the bug of missing assignments for Settings Catalog.

Cheers!

[EndpointManager.zip](https://github.com/Micke-K/IntuneManagement/files/10148258/EndpointManager.zip)

**Comment by dotjesper** [comment]
I have tried out the new functionality and it seems to be working really well!
1. All scripts are exported and readable.
2. Assignments for Settings Catalog policies is now part of the documentation.
Pure awesomeness, I bow and salute you!

Thanks

**Comment by Micke-K** [comment]
Hello

Fix included in 3.8.1

Let me know if I can close this issue

Cheers!
