### ISSUE TITLE
Unable to Export ES Profiles with a target of mdm,microsoftSense

### ISSUE THREAD

**Issue by robbambs** [Micke-K/IntuneManagement#108]
Hi Guys,
I'm currently unable to export the newer profiles that have had the updated templates applied (ones with the target of 'mdm,microsoftSense') from the Endpoint Security Blade. They don't appear in the Endpoint Security portion of the Management Master when listing the profiles.
Anyone else having this issue?
This is the case for ASR profiles or Endpoint Detection and Response, seemingly anything with the microsoftSense target?
See attached screenshots for further info.
![IntuneASR](https://user-images.githubusercontent.com/82602750/212333775-b8463f14-9907-4cb2-97fe-61c94e6c12d9.jpg)
![IntuneMasterASR](https://user-images.githubusercontent.com/82602750/212335188-0084578d-9b1e-4d25-afe6-7b0b41a896c1.jpg)

**Comment by Micke-K** [comment]
Hello!

Check under the SettingsCatalog folder. Some of the Endpoint Security policies are actually Setting Catalogs in the background. 

Cheers!
