### ISSUE TITLE
Export of some Conditional Access Policies Not Working

### ISSUE THREAD

**Issue by rmsyguan** [Micke-K/IntuneManagement#109]
I noticed if the conditional access policy includes a grant action that involve the new control of "Require Authentication Strength" OR assignment that was configured for Workload Identities, you can export these policies but if you try to import them it doesn't work (not imported).

**Comment by Micke-K** [comment]
Hello!

Thank you for reporting this. I found the issue and will include it in the next release.
I am currently going through all the changes but it might take another week or two. You can try the changes by downloading the attached file and replace the existing EndpointManager.psm1.

Let me know how it goes.

Cheers

[EndpointManager.zip](https://github.com/Micke-K/IntuneManagement/files/10424264/EndpointManager.zip)

**Comment by rmsyguan** [comment]
Hi Mick, thanks for the prompt response, I have tried to replace the EndpointManager.psm1 with the one you have shared but I still have the same issue. CA Policies that involve workload identities and auth strength are still not imported unfortunately.

**Comment by Micke-K** [comment]
Weird. That helped my import. I just had one grant criteria. 
Do you have multiple grant settings? 
Can you attach the json for it?

Cheers!

**Comment by rmsyguan** [comment]
Here are the json files that cant be imported on my end

[NotImported.zip](https://github.com/Micke-K/IntuneManagement/files/10425863/NotImported.zip)

**Comment by rmsyguan** [comment]
I see no worries but thanks for looking and working on it. 
Just keep us posted once you had a chance to fix these issues. 
Appreciate it! Thank you!

**Comment by Micke-K** [comment]
Hello

I added support for Importing/Exporting Authentication Strengths objects in 3.8.1.

It should work if the referenced objects are imported before the Conditional Access objects. Bulk import will take care of that if Authentication Strengths objects are exported.

I will look into the other issues as well when I have time.

Cheers!

**Comment by rmsyguan** [comment]
Thanks mike, yes, I can confirm that the auth strength import export works now as long as you also include the auth strength options. It is the same for the authentication context. I manually created them first again in my second tenant and the import works for the CAs that have reference to it.
Right now, the only policies that is not working for the import export on my end are the policies that touches the workload identities and also the one that have sign-in frequency condition.

But overall thanks again for your time working on these items.

**Comment by Micke-K** [comment]
Hello

Sorry for late reply. It's been very busy and I had to learn about Workload Identities and CAs.
I can now import all policies. Try with the new files in the attached zip.

- You have to have a Workload Identities Premium license assigned to the user importing the CA. The Workload CAs will fail otherwise
- I've added support for Export/Import of Authentication Context 
- I added dependency Authentication Context as a dependency for Conditional Access
- I fixed a weird problem that one of the properties for Session Controls had to be null and not false
- plus a few other things that will be included in the next release. 

[MSGraph.zip](https://github.com/Micke-K/IntuneManagement/files/10730530/MSGraph.zip)

Let me know how it goes

Cheers

**Comment by rmsyguan** [comment]
Hey Mike, yup i have just tested it and it works perfectly fine now on importing the CA policies and you are correct, for the workload identities, your tenant must be licensed for it first.
Again, thanks for the updates you made on the tool! :)

**Comment by Micke-K** [comment]
Closing this issue.

Cheers!
