### ISSUE TITLE
Endpoint Security and Setting Catalog profiles missmatch 

### ISSUE THREAD

**Issue by arpsga** [Micke-K/IntuneManagement#110]
When accessing one specific tenants, some categories from the endpoint security blade are listed under settings catalog. 
- EDR 
- ASR
- a few account protecion policies 
- Firewall 

Those policies were created over the GUI of intune. 
Does somebody in the community know a possible cause for this issue?
Other tenants are working fine.

**Comment by Micke-K** [comment]
Hello!

Those policies are technically Settings Catalog in the background. So Intune gets them by using the same API. If you see them under Settings Catalog in Intune, it sounds like the filtering is not working properly. Intune uses filters to exclude these policies in the UI. You can use Dev Mode in the browser to check what URLs and filters it actually uses and see what the API returns. 

No clue why it would show up in one tenant and not the others. Are they still under the Endpoint Security nodes in that tenant? 

Cheers!

**Comment by arpsga** [comment]
Thank you! 
Can you give me a hint what you mean with dev mode in the browser?

**Comment by Micke-K** [comment]
Use F12 in the browser to open Dev Mov. In the there you can look at all the traffic happening in the browser. There will be a lot of going on so it requires some detective work to identify the information you are interested in. 

Happy to have a session about and show you but I won't have time this week. 

Cheers!

**Comment by arpsga** [comment]
I'll close this issue for now. 
Thanks for your valuable help & this great project!
