### ISSUE TITLE
Application - error importing large files

### ISSUE THREAD

**Issue by DennisFleron** [Micke-K/IntuneManagement#112]
Failed to import file 'Adobe_Photoshop_2023_24.1.0.166.json' Exception: Cannot convert argument "val2", with value: "3765310384", for "Min" to type "System.Int32": "Cannot convert value "3765310384" to type "System.Int32". Error: "Value either to bit or to small for a int32."" The file is 3,5gb

**Comment by Micke-K** [comment]
Hello

Can you try the attached file? Just replace the exiting file in the Extensions folder.

Cheers!
[IntuneAppManagement.zip](https://github.com/Micke-K/IntuneManagement/files/10529027/IntuneAppManagement.zip)
