### ISSUE TITLE
copy win + ios wifi profiles

### ISSUE THREAD

**Issue by randomsunrize** [Micke-K/IntuneManagement#114]
Hi thanks heaps for your amazing app.

Found an issue trying to copy a wifi profile. It copies most of it with the trusted cert profiles attached except for the cert profiles for server validation. Tried windows and ios wifi profiles.

Add  () to navigation property rootCertificatesForServerValidation

Failed to invoke MS Graph with URL https://graph.microsoft.com/beta/deviceManagement/deviceConfigurations('6664670f-d2e1-4bbd-81ce-07710a55199c')/microsoft.graph.windowsWifiEnterpriseEAPConfiguration/rootCertificatesForServerValidation/$ref (Request ID: 2bee3189-f35b-4dc2-b0f8-f2767724f142). Status code: BadRequest. Response message: No OData route exists that match template ~/singleton/navigation/key/cast/navigation/$ref with http verb PUT for request /DeviceConfiguration_2301/StatelessDeviceConfigurationFEService/deviceManagement/deviceConfigurations('6664670f-d2e1-4bbd-81ce-07710a55199c')/microsoft.management.services.api.windowsWifiEnterpriseEAPConfiguration/rootCertificatesForServerValidation/$ref. Exception: The remote server returned an error: (400) Bad Request.

Add  () to navigation property rootCertificatesForServerValidation

Failed to invoke MS Graph with URL https://graph.microsoft.com/beta/deviceManagement/deviceConfigurations('99a02b53-54b0-4b93-b96d-ed585757817e')/microsoft.graph.iosEnterpriseWiFiConfiguration/rootCertificatesForServerValidation/$ref (Request ID: 0f82a75f-84c8-4ff2-8af3-c050e1003547). Status code: BadRequest. Response message: No OData route exists that match template ~/singleton/navigation/key/cast/navigation/$ref with http verb PUT for request /DeviceConfiguration_2301/StatelessDeviceConfigurationFEService/deviceManagement/deviceConfigurations('99a02b53-54b0-4b93-b96d-ed585757817e')/microsoft.management.services.api.iosEnterpriseWiFiConfiguration/rootCertificatesForServerValidation/$ref. Exception: The remote server returned an error: (400) Bad Request.

**Comment by Micke-K** [comment]
Hello!

Thank you for reporting this. I'll have a look next week. It's been a crazy week. 

Cheers!

**Comment by Micke-K** [comment]
Hello

Can you please test with this? Just replace the three existing psm1 files in extensions. I included a couple of other fixes as well.

I've tested copy and export\import. Looks like they have changed and now allows multiple reference objects eg in this case multiple Server verification certificates.

Cheers!

[EndpointManager.zip](https://github.com/Micke-K/IntuneManagement/files/10610432/EndpointManager.zip)

**Comment by randomsunrize** [comment]
Awesome got it going with the new extensions!
Thanks heaps

**Comment by Micke-K** [comment]
Issue fixed. Closing. 
Let me know if you have any other issues.
Cheers!
