### ISSUE TITLE
Guest user in tenant, option to select tenant, or enter tenant id

### ISSUE THREAD

**Issue by RogerHaugen** [Micke-K/IntuneManagement#12]
@Micke-K 
For MSP's i think it would be useful, if we could use our "Guest" account(with the correct permissions).

After login, a selector for available tenants or a input for tenant id.

A tenant switcher would also be cool, so you dont have to start again

**Comment by Micke-K** [comment]
I am working on it :)

I am rewriting it from more or less scratch. I am using MSAL for authentication and you will be able to switch account. Hopefully the first version will come in the next few weeks.

**Comment by Micke-K** [comment]
Version 3 Beta 1 released - You can now login with another user or switch tenant (must be enabled in settings)
