### ISSUE TITLE
Silent Documentation from previously exported config

### ISSUE THREAD

**Issue by martincaddick** [Micke-K/IntuneManagement#123]
Having previously exported my config using an AppId, TenantId and CertThumbprint (which is bloody awesome btw) I have all my config in json files in the correct folder structure.
I then want to silently document it using markdown as the output format.
I've done the BulkDocumentationType and saved the config to create a BulkDocument.json file

I can see this in the core.psm1 and can manually make it happen (again, awesome!)

        $settingObj = (ConvertFrom-Json (Get-Content -Path $global:SilentBatchFile -Raw -ErrorAction Stop))
        Invoke-ModuleFunction "Invoke-SilentBatchJob" $settingObj       

Is there another way I should be doing this?

**Comment by Micke-K** [comment]
Hello!

Bulk documentation during a batch job should work. I haven't tried every possible option but I did a test a while back and it was working.

You say you exported your settings, are you doing an offline documentation? What documentation options do you use? What does the log file say?

Cheers!

**Comment by martincaddick** [comment]
Still getting a bunch of these errors
<img width="555" alt="image" src="https://user-images.githubusercontent.com/73564857/227413843-2465a8a0-ccbd-4742-9576-1509140fbad3.png">

This is the script I'm running and it generates a 4.5M markdown file (Took 27 minutes to export and document)
```
$startTime = Get-Date
# NonProd Tenant
$ApplicationId = 'xxxxx'
$CertificateThumbprint = 'xxxxxx'
$TenantId = 'xxxxxxx'
$fileLocation = "C:\github\Non-Production"
$markdownDocSettings = ($fileLocation + "\IntuneManagement\BulkDocumentationDestinationMarkdown.json") 

# Export the configuration
C:\github\IntuneManagement\Start-IntuneManagement.ps1 -Silent -TenantId $TenantId `
-SilentBatchFile ($fileLocation + "\IntuneManagement\BulkExport.json") `
-AppId $ApplicationId `
-Certificate $CertificateThumbprint `
-ShowConsoleWindow

# Document the settings into a single markdown document
$settingObj = (ConvertFrom-Json (Get-Content -Path $markdownDocSettings -Raw -ErrorAction Stop))
Invoke-ModuleFunction "Invoke-SilentBatchJob" $settingObj    

$endTime = Get-Date
Write-Host "Processing time is"($endTime-$startTime)
```
And the json files
[BulkDocumentationDestinationMarkdown.json.txt](https://github.com/Micke-K/IntuneManagement/files/11058114/BulkDocumentationDestinationMarkdown.json.txt)
[BulkExport.json.txt](https://github.com/Micke-K/IntuneManagement/files/11058115/BulkExport.json.txt)

**Comment by Micke-K** [comment]
I'm going through the issues for the next release and found this ad realized I never replied to it. So sorry about that!

I do expect a lot of these warning. I get lots of them as well. To be honest , I don't even remember exactly what all of the means. Sometimes some settings will not have a description in the language files, sometimes these are generated when a parent property is not set etc. The documentation scripts for Template policies is quite complex so make sure it's all documented as expected. Raise another issue if not.

Is there anything else in this issue that you need answers for or can I close it?

Btw....what MD viewer do you use for that kind of large documents? When I created very large MD files, I could not even open them. 

Cheers!

**Comment by martincaddick** [comment]
I've been slack too ;-) Now in Europe for a few months but still progressing this stuff. My preferred markdown editor is Typora but it still struggles with the 4M file. I've reverted to using the html output which is clean at 7.5M.
Also, when I'm using markdown I really try hard to keep html out of the markdown. Means compromises on the data in tables and in some of them I still just have System.Collection type of responses.
Re: this issue. Lets close it.
