### ISSUE TITLE
Missing policies

### ISSUE THREAD

**Issue by RogerHaugen** [Micke-K/IntuneManagement#13]
If you create policies under these nodes, they dont seem to show up in the UI

![image](https://user-images.githubusercontent.com/38752867/108226094-db878400-713c-11eb-8cca-7252485e2904.png)

**Comment by Micke-K** [comment]
These should come up under baseline profiles. They are all the same object type, with different templateId property.
I have tested and verified export/import in the next version.

**Comment by RogerHaugen** [comment]
So it dosent work on the current version?

**Comment by Micke-K** [comment]
I just checked. Those policies are located in the Baseline Profiles node

**Comment by Micke-K** [comment]
Version 3 Beta 1 released - Enpoint Security policies included with correct name of node

**Comment by Micke-K** [comment]
Version 3 Beta 1 released - Enpoint Security policies included with correct name of node
