### ISSUE TITLE
Core.psm1 attempts to run CloudAPI... from github instead of local

### ISSUE THREAD

**Issue by martincaddick** [Micke-K/IntuneManagement#130]
When running without internet access scripts tries to run CloudAPI* fro mgithub instead of local

<img width="623" alt="image" src="https://user-images.githubusercontent.com/73564857/233543296-7c0e50b1-f652-46b4-b62c-84bc7788bde4.png">

**Comment by Micke-K** [comment]
Hello!

Running without internet access? What are you trying to do offline?

It tries to connect to GitHub to check current version. It does not try to run it. I should add error handling though. 

Cheers!

**Comment by Micke-K** [comment]
Closing the issue. Please reopen if there still is a problem.

Cheers!
