### ISSUE TITLE
3.9.0 Saying it's 3.8.x and needs updating!

### ISSUE THREAD

**Issue by ckasprzak** [Micke-K/IntuneManagement#132]
Just grabbed the latest and it was saying it wasn't the latest!

**Comment by Micke-K** [comment]
Hello!

Sorry about that. Should not release late at night. Missed updating the module file. I updated the psd1 file and Release in GitHub.

Thank you for reporting it.

Cheers!

**Comment by Micke-K** [comment]
Issue fixed. Closing.

Cheers!
