### ISSUE TITLE
Documentation: Offline feature prompts for creds

### ISSUE THREAD

**Issue by dridley23** [Micke-K/IntuneManagement#138]
**Bug**
When using exported files to produce word document, it prompts for creds. But you can use any creds to get past it.
Expectation: No creds required. No prompt.

Note: It's no biggy if this isn't resolved. It's more FYI.

**Comment by Micke-K** [comment]
Yo!

Full offline documentation will never work. It will always require access to Graph. Just not necessarily the tenant you exported from. Custom imported ADMX files might require full access to tenant. 

Reason is simple. Lots of policies like ADMX, Settings Catalog, Endpoint Security etc. gets the language strings from Graph. Template, Conditional Access, Compliancy policies etc. uses the language files. 

Cheers!

**Comment by dridley23** [comment]
Thanks, reason enough! Not a bug then...just me.
Keep up the awesome work! I love it.
