### ISSUE TITLE
Feature Request: Comparison View

### ISSUE THREAD

**Issue by aelri-c** [Micke-K/IntuneManagement#14]
Hi Micke-K 

Is there a roadmap to have a comparison feature. i.e. create an intune policy, export that golden image policy to json file and then later do a comparison to check if there as been any changes?

**Comment by Micke-K** [comment]
I have thought about having some kind of comparison feature in there but no implementation plans yet. I have another major change I am focusing on at the moment. 

There are ways of doing this manually eg I export policies and then use a file comparison tool like Tortoise Diff to check what's changed.  Not the optimal solution but can be used until something better is developed.

**Comment by Micke-K** [comment]
Comparison implemented. Closing the issue.
