### ISSUE TITLE
Documenting - no word option

### ISSUE THREAD

**Issue by Jien-hub** [Micke-K/IntuneManagement#140]
When trying to document - the only options I have are Markdown, CSV and HTML. I read you can export to word?

Update from Logs - Failed to add Word Interop type. Cannot create word documents. Verify that Word is installed properly. Exception: Could not load file or assembly 'Microsoft.Office.Interop.Word, Version=12.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c' or one of its dependencies. The system cannot find the file specified.

**Comment by Micke-K** [comment]
Hello!

The script will check if Word is installed by trying to create a Microsoft.Office.Interop.Word object. If that fails, Word will not be listed as an option in the documentation form. 

Do you have Word installed?

Cheers!

**Comment by Jien-hub** [comment]
Yes I actually do! Its office Microsoft 365 version so not sure if it will impact the creation of the object?

**Comment by Micke-K** [comment]
Great news and thank you for the kind words!

Can we close this now?

Cheers!
