### ISSUE TITLE
Device Configuration not loading all config profiles

### ISSUE THREAD

**Issue by jh-kca** [Micke-K/IntuneManagement#144]
Device Configuration only displaying 47 of 140+ configuration profile objects.

**Comment by Micke-K** [comment]
Hello!

Are the missing profiles different types eg Setting Catalog or Administrative Templates? 

Each menu item is one API, Device Configuration in the portal is combining them into one. 

Cheers!

**Comment by jh-kca** [comment]
Hi Micke,

Thanks for the quick response.

There is a mix of both Admin template and Settings catalog profiles missing.  I’ve found most of the missing ones in Settings Catalog now but still missing ~15.


Best regards,

Joanne Haggart
Senior Infrastructure Engineer
KCAD-IT
Office:    +44 (0)1224 987 853
Email:   ***@***.***

We welcome a new era for KCA Deutag with the integration of
Saipem onshore drilling business blending two great teams.

***@***.***

***@***.***

KCA Deutag Drilling Ltd
Group Headquarters, Bankhead Drive, City South Office Park, Portlethen, Aberdeenshire, AB12 4XX

#drivetozero #stopthejob #customercentricity #cultureofcare #enhancethebrand

To see our website, go to  www.kcadeutag.com<http://www.kcadeutag.com/>


[Well of Innovation Campaign - automatic email footer design 3]

**Comment by Micke-K** [comment]
Hello!

They should be there somewhere. Do you know what policy types that are missing?

Cheers!

**Comment by jh-kca** [comment]
Thanks Micke,

I’ve found them now – hiding under Administrative Templates which I thought was just the ADMX files.

It’s a great tool – many thanks for creating.

Best regards,

Joanne Haggart
Senior Infrastructure Engineer
KCAD-IT
Office:    +44 (0)1224 987 853
Email:   ***@***.***

We welcome a new era for KCA Deutag with the integration of
Saipem onshore drilling business blending two great teams.

***@***.***

***@***.***

KCA Deutag Drilling Ltd
Group Headquarters, Bankhead Drive, City South Office Park, Portlethen, Aberdeenshire, AB12 4XX

#drivetozero #stopthejob #customercentricity #cultureofcare #enhancethebrand

To see our website, go to  www.kcadeutag.com<http://www.kcadeutag.com/>


[Well of Innovation Campaign - automatic email footer design 3]
