### ISSUE TITLE
'/' sign in tenant name blocks export

### ISSUE THREAD

**Issue by Nouneds** [Micke-K/IntuneManagement#150]
Hello Micke,
during bulk export through silent batch job we encountered an error. 
When '/' or '\'  ' ' sings are used in tenant name the export fails as it cannot find a path.

"Could not find a part of the path 'Backup\BackupExported\XXXX A\S \AdministrativeTemplates'."

Obviously it tries to set up a 'XXXX A\S ' as subpath which is problematic. 
Is there a way to export without actually changing a tenant name ?

**Comment by Micke-K** [comment]
Hello,

That was a new one :) 

I'll have a look at this. I'm overseas at the moment but I'm planning a new release and I should be able to include this one. 

Cheers

**Comment by Micke-K** [comment]
Hello!

This is implemented in the latest version. 

Please have a try and let me know if it is working. 

Cheers!

**Comment by Micke-K** [comment]
Closing this.

Please re=open the case if it is not working.

Cheers!
