### ISSUE TITLE
Is it possible?

### ISSUE THREAD

**Issue by edthefixer** [Micke-K/IntuneManagement#152]
### Discussed in https://github.com/Micke-K/IntuneManagement/discussions/151

<div type='discussions-op-text'>

<sup>Originally posted by **edthefixer** July 12, 2023</sup>
Fantastic tool and I use it to provide detailed information of tenants configurations on most of my engagements to clients but I was wondering if there is more that can be extracted from Azure rather such as Sentinel configuration? Example specific Notebooks and their rules.</div>

**Comment by Micke-K** [comment]
Hello,

Thank you!

There are no plans to include additional Azure information. That doesn't mean it won't be. The tool is "very easy" to extend. If the information is in graph it could be added. 

Cheers!

**Comment by Micke-K** [comment]
Closing this but will keep it in mind.

Cheers!
