### ISSUE TITLE
Support for  Driver updates for Windows 10 and later?

### ISSUE THREAD

**Issue by Rens199991** [Micke-K/IntuneManagement#154]
Hi
First of all, your tool is fantastic!

I was wondering where the json files of the new driver update feature in Intune are stored?
I created manually the policies in Intune but i'dont find them in the GUI of your tool. 

Or is this not yet supported in the latest version?

**Comment by Micke-K** [comment]
Hello and thank you!

Not supported yet. I've added it but I need to finish the release. I am currently on holidays to visit family but I'll try to release it soon. It's almost ready. 

Cheers!

**Comment by Rens199991** [comment]
Great! Thanks for the quick response! :) 

Enjoy your holiday

**Comment by Micke-K** [comment]
Hello!

This is implemented in the latest version. 

Let me know if I can close this issue. 

Cheers!

**Comment by Rens199991** [comment]
Nice! Thank you.

Keep up te great work. Tested it and it works.

Of course you may close this issue.
