### ISSUE TITLE
Configuration profiles missing Windows firewall

### ISSUE THREAD

**Issue by NeruaX** [Micke-K/IntuneManagement#156]
Did some testing and seems like the windows at least firewall is missing from export.
From my testing
"deviceManagement/configurationPolicies"
lacks the windows firewall but
"deviceManagement/configurationPolicies?`$filter=templateReference/TemplateFamily%20eq%20%27endpointSecurityFirewall%27"
includes it

Im assuming Microsoft changed something as this seems new to me OR this is just a temporary error, but even just running in powershell it seems replicateable in my environments.

**Comment by Micke-K** [comment]
Hello,

Did you check under Settings Catalog?

I can see my Endpoint Security FW policies there. 

Cheers!

**Comment by NeruaX** [comment]
I did.
I believe when microsoft updated the the firewall settings to templates instead of settings catalog. Try it with a new policy instead of an existing.

**Comment by NeruaX** [comment]
Interesting. Well...Ill assume its me doing something wrong then.

I appreciate your work and thank you for making it avaliable.

**Comment by Micke-K** [comment]
No problem. 

It's interesting though. Not sure why you wouldn't see them under Settings Catalog. 

Have you tried in Graph Explorer? 

Cheers!
