### ISSUE TITLE
Failed to export object Exception: Cannot validate argument on parameter 'Name'.

### ISSUE THREAD

**Issue by durrante** [Micke-K/IntuneManagement#16]
Hi there,

Thanks for this awesome tool, I've been using it for a while now, I've recently ran into this issue when bulk exporting configurations, 'Failed to export object Exception: Cannot validate argument on parameter 'Name'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.'

This has pretty much happened on every object, but it is rather inconsistent, only half of my configuration profiles have been exported. 

Also, this has only just started recently, I downloaded a version 4 weeks ago that is working fine, seems to be with the latest version that this error persists.

Any ideas?

**Comment by Micke-K** [comment]
I'll have a look. I know there is an issue with the permissions I did in the last change but can't see how that could cause this. I'll have a check soon as possible.

**Comment by Micke-K** [comment]
This is a bug that happens when exporting objects with assignments configured and the option "Export Assignments" is not checked. This will be fixed in the next release which is hopefully is this week. There are few other changes that needs to be tested as well.
Workaround for now: Make sure "Export Assignments" is checked during export.

**Comment by Micke-K** [comment]
New version uploaded. Please test it and let me now how it goes.
Thank you so much for reporting the bug and using the tool!

**Comment by durrante** [comment]
No Mikael, thank YOU for this tool, I love it and it comes in super handy! It's my number one Intune tool.

Thanks again for looking into the bug and development of this project. 👍
