### ISSUE TITLE
missing information when export conditional access policy in word documents

### ISSUE THREAD

**Issue by ngjrjeff** [Micke-K/IntuneManagement#168]
if conditional access policy has configured "filter for devices" under conditions, this information is not captured when export into word document.

**Comment by Micke-K** [comment]
Hello!

Thank you for reporting this. Can you try the attached file and let me know if it is ok?

Note: That it will only document the actual Rule and not translate it to nicer display format.

Cheers! 

[DocumentationCustom.zip](https://github.com/Micke-K/IntuneManagement/files/12836332/DocumentationCustom.zip)

**Comment by ngjrjeff** [comment]
> Hello!
> 
> Thank you for reporting this. Can you try the attached file and let me know if it is ok?
> 
> Note: That it will only document the actual Rule and not translate it to nicer display format.
> 
> Cheers!
> 
> [DocumentationCustom.zip](https://github.com/Micke-K/IntuneManagement/files/12836332/DocumentationCustom.zip)

hi Micke

the attached file worked by document the actual rule of the "filter for devices" under conditions.
