### ISSUE TITLE
Feature Request: Change API version from Beta to v1.0

### ISSUE THREAD

**Issue by nathangraham-MSFT** [Micke-K/IntuneManagement#170]
Would it be possible to add in a radio button or drop down into the settings section to select which API version is used, either Beta or v1.0.

I ran into an issue where the beta query for Device Configuration was timing out but worked fine with v1.0. I had to update the MSGraph module to fix the issue, but this may be overwritten with future updates.

**Comment by Micke-K** [comment]
Hello,

It could easily be done but with unknown consequences. Lots of the APIs and some of the properties used are only available in the Beta version. So lots of things might break but hard to say exactly what. 

Cheers!

**Comment by Micke-K** [comment]
Hello,

I've included this in the next release. I did a quick test and this will break some features eg ADMX. 

Cheers!

**Comment by Micke-K** [comment]
Included in 3.9.2
