### ISSUE TITLE
Setting Name does not export properly on some tables

### ISSUE THREAD

**Issue by DesmondBellingerSolvus** [Micke-K/IntuneManagement#174]
Hello we have been using this tool for documentation of our intune environment and we have been loving it so far. The one issue that I have been having is that on some of the tables generated by the where the format is [Name | Value] or [Name | Status | Value], the name does not export, leaving the cell blank. 

I've tried exporting to both word and html with the same result.

Below is an exported word doc showing the missing names
[Documentation-2023-11-09.docx](https://github.com/Micke-K/IntuneManagement/files/13310338/Documentation-2023-11-09.docx)

**Comment by Micke-K** [comment]
Hello!

I had a look at this. I cannot reproduce this. I tried with both built in Administrative Template settings policy and a policy form an imported ADMX file. 

Something is wrong because there is no Category row. Not sure how that would happen either. 

What Output Properties and Output Level do you use?

Is it the same result if you do a HTML output? I'm trying to figure out if the problem is the collector or the output provider.

Cheers!

**Comment by DesmondBellingerSolvus** [comment]
Thanks for the quick reply. The output is identical no matter what format I select. Where would I be able to see the output level and properties? 
![image](https://github.com/Micke-K/IntuneManagement/assets/144938973/43708a8a-e94a-48dd-b51e-8dd7951c4a4e)
[Settings file.json](https://github.com/Micke-K/IntuneManagement/files/13321299/Settings.file.json)
I've attached an export of the application settings as well as an image of the Output settings tab.

**Comment by Micke-K** [comment]
Hello,

If you get the same issue on HTML etc. then there is an issue when collecting information. Do you document from Intune or from an exported folder. If you document from exported folder, are you logged in to the same tenant as the export? 

Do you only get this on Administrative Templates or other policies as well?

Output level and Properties is only available for the Word Output provider. 

Cheers!

**Comment by Micke-K** [comment]
Hello,

Can you try this? Documentation would not work when swapping between tenants. If that is what you did.

Cheers!

[Documentation.zip](https://github.com/Micke-K/IntuneManagement/files/13324425/Documentation.zip)

**Comment by DesmondBellingerSolvus** [comment]
Hi just to answer your questions: we are documenting directly from Intune.
The issue does only seem to affect Administrative Templates profiles. 
I placed the file above in the extensions folder but it seems like I'm still getting the same results.

**Comment by Micke-K** [comment]
Hello!

That is very strange. I kind of know what's happening but can't explain it. The script uses an API to get settings information for ADMX policies and for some reason that is not working in your environment. Any hints in the log file? There should be graph errors if an API call fails. 

Cheers!

**Comment by DesmondBellingerSolvus** [comment]
Looking at the logs I see a few errors:

This one as a log in:
Missing scopes: User.ReadWrite.All,Policy.Read.All,Policy.ReadWrite.ConditionalAccess,Application.Read.All,Agreement.ReadWrite.All,Organization.ReadWrite.All,CloudPC.ReadWrite.All

And one as documentation is attempted:
Failed to invoke MS Graph with URL https://graph.microsoft.com/beta/deviceManagement/groupPolicyDefinitions('5efa5eff-a8f6-46ba-a7cb-4e6d77631754') (Request ID: eee22664-dec8-4972-92b9-4c53e1b61f8f). Status code: Unauthorized. Response message: Access token validation failure. Invalid audience. Exception: The remote server returned an error: (401) Unauthorized.

The above error occurs 3 times followed by this:
Could not find definition for definition id ''. Values might be documented in the wrong order!

The section documented was the same one that I originally attached.

**Comment by Micke-K** [comment]
Hello,

Thank you for that. It explains the issue and I think I found the reason behind it. It's hard for me to test and verify since this would only happen in GCC environments (+ all other non-public environments).

Can you try this version?

Cheers!

[Documentation.zip](https://github.com/Micke-K/IntuneManagement/files/13402066/Documentation.zip)

**Comment by DesmondBellingerSolvus** [comment]
That worked, thank you very much!

**Comment by DesmondBellingerSolvus** [comment]
Just following up on the issue, after making a successful export of all of our Intune information, I checked the logs again and noticed that there were still quite a few Graph errors being thrown. Given the fact that it's probably hard to test outside of commercial, I figured you might be interested in the snippet of log file from that export. 
[Log11-20.txt](https://github.com/Micke-K/IntuneManagement/files/13418045/Log11-20.txt)
