### ISSUE TITLE
Can't document or view anything under "Intune Info"

### ISSUE THREAD

**Issue by X-15** [Micke-K/IntuneManagement#176]
Hi,
thanks again for this great tool. Unfortunately I can't document anything in here... 
<img width="766" alt="image" src="https://github.com/Micke-K/IntuneManagement/assets/4459707/c98aa0a7-2f8b-4442-bb6a-a2b8e4fad3e3">

All documents turn out blank

Do you need some kind of log or do I need some special permissions?

**Comment by Micke-K** [comment]
Closing this. I might revisit this in the future. It would be nice to have.
