### ISSUE TITLE
cannot import to another tenant

### ISSUE THREAD

**Issue by ngjrjeff** [Micke-K/IntuneManagement#177]
i export configuration file from one tenant and trying to import to another tenant but it fails.
hmm. anyone has any idea why and where i should look into? thanks.

![Untitled](https://github.com/Micke-K/IntuneManagement/assets/57741083/104832a1-607f-49c9-a4eb-ec8f95845a2d)

**Comment by Micke-K** [comment]
Hello,

Looks like an Android App Config that failed.

Does the app exist in the target environment?

What app was it for and what settings did you use? Any chance you can attach the policy? Or upload a documentation html or md of the policy?

Cheers!

**Comment by ngjrjeff** [comment]
Thanks Micke. It is because the app was not exist in target environment. After i made the app exist in target environment and then import the app config, it is successful.
