### ISSUE TITLE
Import Administrative Templates error

### ISSUE THREAD

**Issue by enroll-bacon** [Micke-K/IntuneManagement#18]
Updated to build 3.1.3 and import of Administrative Templates does not function.

Error message from the CloudAPIPowerShellManagement log
Failed to invoke MS Graph with URL https://graph.microsoft.com/beta/deviceManagement/groupPolicyConfigurations . Status code: BadRequest	

Other imports seems to function as they should

**Comment by Micke-K** [comment]
Thank you for reporting this. New version uploaded. Sorry about this!

**Comment by enroll-bacon** [comment]
Works like a charm now. Thank you
