### ISSUE TITLE
Can't start IntuneManagement

### ISSUE THREAD

**Issue by coem0** [Micke-K/IntuneManagement#188]
Stuck as Authenticate in the GUI. And in Powershell stuck at Use Graph environment: graph.microsoft.com.
It worked yesterday, tried downloading the IntuneManagement package again, but still the same problem. 

![AuthProblem](https://github.com/Micke-K/IntuneManagement/assets/41294245/9923f17f-5aaa-45b7-92d3-fc6508eeca9c)

**Comment by Micke-K** [comment]
Hello,

Blocked by proxy? I know that the login can hang if it can't reach the login environment.

You could also try to delete/rename "C:\Users\micke\AppData\Local\CloudAPIPowerShellManagement\msalcahce.bin3

**Comment by Micke-K** [comment]
Hello,

Blocked by proxy? Login could hang if it can't connect and authenticate.

You could also try to delete/rename %LOCALAPPDATA%\CloudAPIPowerShellManagement\msalcahce.bin3

That holds the token cache.

Cheers!

**Comment by coem0** [comment]
Works bý deleting the cache, thanks.
