### ISSUE TITLE
Multiple backup folder when using %DateTime% variable

### ISSUE THREAD

**Issue by AIGARSJ** [Micke-K/IntuneManagement#189]
If export job happens longer that 1 min, IntuneManagement application creates multiple folder.
![image](https://github.com/Micke-K/IntuneManagement/assets/15418150/bf7207b6-dd21-4741-a99e-c7a99847efcf)
Export job should create only single folder with backup start date and time.

**Comment by Micke-K** [comment]
Hello,

Thank you for reporting this. I've fixed this in the next version. I'll try to release it soon.

Any reason you use %DateTime% instead of just %Date%? 

Cheers!

**Comment by Micke-K** [comment]
Closing this since fix was included in official release.
