### ISSUE TITLE
Documentation feature does not replace illegal character in Configuration name

### ISSUE THREAD

**Issue by SasStu** [Micke-K/IntuneManagement#19]
I just tried to document several configuration profiles which contain a "/" in the configuration name. The documentation feature is unable to save the CSV files probably caused by the illegal character for a Windows filesystem.

![image](https://user-images.githubusercontent.com/28406607/124606761-7a531980-de6d-11eb-8c59-d98fdcaf147a.png)

Maybe you could add to row 3677 in Extensions/Documentation.psm1 something like this:

$itemsToExport | Out-File ($folder + "\$($objName.Split([IO.Path]::GetInvalidFileNameChars()) -join '_'
).csv") -Encoding UTF8 -Force

Thanks for the great tool btw!!!

**Comment by Micke-K** [comment]
Thank you for the bug report!

I uploaded a new version. Please test it at let me know how it goes. 

There were a few other places with the same issue + I fixed a few other bugs. Have a look at the ReleaseNotes for more info. 

Thank you!

**Comment by SasStu** [comment]
It works, great thanks for the quick fix!
