### ISSUE TITLE
Compare Intune tenants

### ISSUE THREAD

**Issue by Influencer101** [Micke-K/IntuneManagement#203]
Hi, I'm looking for a way to compare different tenants to standard baseline(s). While it seems the tool can be used to compare the configuration of an Intune tenant with an exported config, it doesn't seem possible to compare a tenant with an export of another tenant due to different object IDs. Is this a correct assessment, and do you have plans to add this capability? Maybe if the compare could be automated/scripted, then this would offer a solution to compare Intune configurations against exported configurations. Thanks, and great job on what you've accomplished so far

**Comment by Micke-K** [comment]
Hello,

Yes, it will have a few differences like ID, last modified, created etc. I normally open the csv in excel and filter out those properties. 

This is also something I am currently looking into. I have many ideas for the compare functionality. In fact, I'm looking into a redesign of many of the features. However, all the changes takes longer than I thought for many different reasons.

Cheers!

**Comment by DanClowry** [comment]
I have created a small Powershell script that copies the IDs from one set of exported policies to another so they can be compared using the "Files in Exported Folders" option. It uses the exported file name to determine if the policies are the same so the policies must have the same name in the baseline & comparison tenant. The script was written in 30min so it probably doesn't cover edge cases but works well enough for me.

https://gist.github.com/DanClowry/893b97b33805a17bd64f4b316e246412

Usage:
1. Export the objects from your baseline tenant
2. Export the objects from the tenant you want to check
3. Run the following command replacing the paths with wherever you exported the files: `.\DuplicateIntuneManagerIds.ps1 -BaselinePath C:\temp\OpenIntuneBaseline-main\WINDOWS\ -TenantExportPath C:\temp\export\Contoso\`
4. Compare the two folders in IntuneManagement using the "Files in Exported Folders" option - IntuneManager will now be able to properly compare the policies and identify any differences.

**Comment by Micke-K** [comment]
Hello,

Thank you so much! I'll have a look at this. 

I did some minor updates to compare in the last version but still have a few more things to add. 

Still working hard on the new version. This will be way easier to implement there but I'll see what I can do in meantime. It should be fairly easy to implement in the existing version as well. 

Cheers!

**Comment by Micke-K** [comment]
Hello

Can you test this? Replace Xaml files in the Xaml folder and psm1 in the Extensions folder.

I added a new Compare provider "Intune Objects with Exported Files (Name)". This will compare Intune objects with exported files and identify exported objects based on name in file. I renamed the default provider to "Exported Files with Intune Objects (Id)".

I also added a couple of extra Skip options to exclude missing exported files or skipping missing Intune objects. 

I fixed a bug when skipping Basic properties + added ScopeTags as Basic Properties eg matching value will be skipped if you select that.

Let me know how it goes if you test it.

Cheers!

[Compare.zip](https://github.com/Micke-K/IntuneManagement/files/15367385/Compare.zip)

**Comment by DanClowry** [comment]
I've tested with those new files and it's working great. The "Intune Objects with Exported Files (Name)" comparison method correctly identifies what settings differ in the tenant's current policies vs our baseline export. The options to skip missing policies also works great and has made it really easy to compare multiple tenants against our baseline without it getting cluttered with policies unique to specific tenants.

Thanks for adding this in so quick!

**Comment by Micke-K** [comment]
Thank you for the update!

Cheers
