### ISSUE TITLE
"Microsoft Intune PowerShell" is being decommissioned 

### ISSUE THREAD

**Issue by fortijohny** [Micke-K/IntuneManagement#223]
There is now a warning when we launch te application : 
![image](https://github.com/Micke-K/IntuneManagement/assets/168748519/cf4c206a-5cd8-4312-8c04-c6d84f9963f9)

Also, if the application is detected in our tenet, we also get this warning in the admin portal : 

![image](https://github.com/Micke-K/IntuneManagement/assets/168748519/6a3519f4-1217-47a0-98a5-5360ca075014)

**Comment by Micke-K** [comment]
Hello,

Yes, this is expected. The warning is there because Microsoft is decommissioning the PowerShell App in Entra. This was the default app in the tool up until the latest release. 

If you check the box, it will change to the Graph App instead. This can also be changed in Settings. 

Cheers!

**Comment by Micke-K** [comment]
Closing. Default app was change in the release.
