### ISSUE TITLE
Feature Request - Select tenant ID

### ISSUE THREAD

**Issue by dotjesper** [Micke-K/IntuneManagement#23]
Hi,
Great project! This tools have soooo many features and nice additions, the Microsoft Endpoint Manager interface doesn't. I've used its to export and import between tenants - however; working for a Microsoft Partner, and often being invited into a customer tenant, being able to select the tenant ID as part of the login would greatly enhance the usability in these scenarios.

I don't think I've missed anything in the documentation.

Thank you for your great work, very much appreciated!

**Comment by Micke-K** [comment]
Hello!

Thank you so much for the support. 

Are you talking about the Multi-Tenant support? The "Get Tenant list" in Settings will add all Tenants you have access to in the Login Info. You can then swap between tenants without having to login. 

Note that this can cause multiple consent prompts the first time. One for the API that gets the tenant list and then for connecting to the Azure app in the other tenants. 

Restart the app after enabling the setting. The app will always login to your home tenant as default. Just click on the login picture and select another tenant.

Thank you!

**Comment by dotjesper** [comment]
WHOOOT!
"Awesomeness" is just a word but the feeling I whish to send to you, I bow my forehead to the dust!
Thank you!
