### ISSUE TITLE
Baseline policy import 

### ISSUE THREAD

**Issue by Rahulkr023** [Micke-K/IntuneManagement#232]
have some baseline files. How can I import them into the Intune management portal?

**Comment by Micke-K** [comment]
Hello,

How did you export it? If it is exported with the tool, you should be able to import it there as well. 
If it is new baselines, you import them via Settings Catalog. Old baselines can be imported via Endpoint Security.

Old versions of some baselines cannot be imported.

Cheers!

**Comment by Rahulkr023** [comment]
where i can get new baseline profiles  ?

**Comment by Micke-K** [comment]
You generate them in the portal. 

The original baselines were using the Intent API (Endpoint Security). The new are using Settings Catalog API. There is no migration between them. 

What are the baselines you have and where did you get them from?

Cheers!

**Comment by Rahulkr023** [comment]
I have some baseline templates from a GitHub repository (NCSC baseline). I tried to upload them to the portal, but they are not showing after import.

**Comment by Micke-K** [comment]
What URL?

The tool can only import if the files are exported with full OData info. 

Also, the name if the folder is important since it is used to identify which API to use for import.

So there are a few more requirements than just importing a json file. 

Cheers

**Comment by Micke-K** [comment]
Closing this since due to inactivity. Please reopen if it is still an issue.

Cheers!
