### ISSUE TITLE
Tenants not displaying in tenant list if they have "&" in name

### ISSUE THREAD

**Issue by Slogue242** [Micke-K/IntuneManagement#237]
If a tenant display name has "&" it will not display in the drop-down list of tenants, you have access to.

This has been resolved by editing the MSALAuthentication.psm1 file by adding the following:

if ($tenant.DisplayName -like "*&*"){
    $tenant.DisplayName = $tenant.DisplayName.replace('&',"and")
}

![image](https://github.com/Micke-K/IntuneManagement/assets/44891132/29be2fdf-7892-413e-ba77-658eab22cfbf)

**Comment by Micke-K** [comment]
Hello,

Thank you for this! I'll include this in the next release. I found another place with the same issue. 

Cheers!

**Comment by Micke-K** [comment]
Closing this since fix is released. Please reopen if it is still an issue.

Cheers!
