### ISSUE TITLE
Get an error on my screen

### ISSUE THREAD

**Issue by AAvic** [Micke-K/IntuneManagement#238]
Goodmorning,

Im try to use IntuneManagement but getting an error message in my screen. I lookt it up but can't find it.

I have change my Consent and Microsoft Graph Command Line Tools is in my list but still getting the error.

![Schermafbeelding 2024-06-18 091349](https://github.com/Micke-K/IntuneManagement/assets/11776513/7797d655-962f-41be-a818-c667953c1742)

![Schermafbeelding 2024-06-18 091819](https://github.com/Micke-K/IntuneManagement/assets/11776513/72179f30-19a4-4786-806d-8ce6a073911d)

**Comment by Micke-K** [comment]
Hello,

Looks like the app is missing permissions. Click on the profile picture in the top right corner. There should be a "Request consent" link in the there where. This would add the required permissions to the Graph CLI app.

There should be some additional info in the log stating that it is missing permissions. 

Cheers!

**Comment by AAvic** [comment]
Hi,

Im at the tab permissions but i don't have a request consent.

Maybe im doing it wrong
![Schermafbeelding 2024-06-18 152502](https://github.com/Micke-K/IntuneManagement/assets/11776513/6e9c348a-13a0-4d4f-8860-d0388ddc2d0c)
![Schermafbeelding 2024-06-18 152507](https://github.com/Micke-K/IntuneManagement/assets/11776513/1a5aba9b-0aa4-450e-b75f-ab9f03880807)

**Comment by Micke-K** [comment]
Hello,

Permissions are required on the app and must be requested in the app. So basic requirements are:

* You must have permission in Entra to approve/manage Graph CLI Enterprise App
* The Enterprise App must have permission to MS Graph 
* You must have permissions in Intune. 

The MS Graph CLI App permissions can be requested in the IntuneManager via the profile info up in the right corner once you have logged in.

Cheers!

**Comment by Micke-K** [comment]
Closing this. Please reopen if this is still an issue.

Cheers!
