### ISSUE TITLE
Error when exporting Compliance Policies

### ISSUE THREAD

**Issue by dotjesper** [Micke-K/IntuneManagement#24]
Hi,
Great project! This tools have soooo many features and nice additions, the Microsoft Endpoint Manager interface doesn't.

I get this error when exporting Compliance Policies, and choose not to export Assignments - I do not see this error on e.g. Conditional Access og Windows Update policies.

Loading Compliance Policies objects
Export Compliance Policies
Export WS-C-Windows Compliance - Microsoft Defender BitLocker settings
Loading WS-C-Windows Compliance - Microsoft Defender BitLocker settings
Failed to export object Exception: Cannot validate argument on parameter 'Name'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
Export WS-C-Windows Compliance - Microsoft Defender Firewall settings
Loading WS-C-Windows Compliance - Microsoft Defender Firewall settings
Failed to export object Exception: Cannot validate argument on parameter 'Name'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.

Re-enabling Export Assignments, exports all Compliance Policies as expected.

Thank you for your great work, very much appreciated!

**Comment by Micke-K** [comment]
This looks like the same issue as #16 but that was fixed in July.

What versions do you have of the Core and MSGraph modules?  - Check in About

Thank you!

**Comment by dotjesper** [comment]
Holly cow, answers are coming at lightning speed, are you ninja?

Agreed, looks like the same issue as #16. I just downloaded the latest release, that is version 3.1.2 from June 2021.
I´ll download the newest files and retry.

Thank you for your great work, very much appreciated!
