### ISSUE TITLE
IntuneManagment does not update new policies

### ISSUE THREAD

**Issue by sonyszkiewicz** [Micke-K/IntuneManagement#240]
I have created multiple policies and setting catalogues but the app stoped refreshing them and is giving me incomplete resoults
<img width="1418" alt="2024-06-18 20_55_52-Intune Manager" src="https://github.com/Micke-K/IntuneManagement/assets/98872520/8da2bd02-d815-4d06-9a9a-d477299f3c18">

**Comment by Micke-K** [comment]
Hello,

Settings Catalog would be in the Settings catalog policies menu item. 

What does the log say?

Cheers!

**Comment by Micke-K** [comment]
Closing this. Settings Catalog is NOT in the Device Configuration tab. It's in the Settings Catalog menu since it has its own API.

Cheers!
