### ISSUE TITLE
Documentation Word

### ISSUE THREAD

**Issue by UeliTri** [Micke-K/IntuneManagement#246]
Hello

Thank you very much for this valuable tool. It makes my work much easier. 

Unfortunately I cannot get the Word export to run. 

Error Faild to process object. It is not possible to call a method for an expression that has NULL. 

What am I doing wrong?
Thank you very much!

**Comment by Micke-K** [comment]
Hello,

Thank you for the support.

Can you upload the full log? There could be a lot of things that goes wrong.
Can you log to HTML? Would be interesting to see if that output provider works.
What policy are you trying to document? Any chance you can upload the json for it?

Cheers!

**Comment by UeliTri** [comment]
Hi,
HTML works perfectly. It is a policy from the settings catalog.
I have attached the log and json.

Kind regards
[Log.txt](https://github.com/user-attachments/files/16045881/Log.txt)
[mtf365-W10-OneDrive-D-v10.json](https://github.com/user-attachments/files/16045902/mtf365-W10-OneDrive-D-v10.json)
[CloudAPIPowerShellManagement.log](https://github.com/user-attachments/files/16045920/CloudAPIPowerShellManagement.log)

**Comment by Micke-K** [comment]
Thank you for that!

It can register a Word COM object since there is no error about that, but it fails on InvokeMembers and other COM commands. It's like the properties and methods does not exist.

I noticed that you have German OS language. I wonder if that causes it. I can document Settings Catalog objects in English and German without issues. with an English OS. 

I have to see if I can find a way to add some logging to this to identify the issue.

Do you have a computer with English OS and Word you can test on?

Cheers!

**Comment by UeliTri** [comment]
Hello!

Thank you for your help.
I will test it tomorrow on an English machine and report back immediately.

greetings


Freundliche Grüsse

Ueli Tritten

Chrützacher 4
3202 Frauenkappelen
Switzerland

M +41 79 652 59 03
***@***.***
www.tritten.ch

Am 30.06.2024 um 21:59 schrieb Mikael Karlsson ***@***.***>:

﻿

Thank you for that!

It can register a Word COM object since there is no error about that, but it fails on InvokeMembers and other COM commands. It's like the properties and methods does not exist.

I noticed that you have German OS language. I wonder if that causes it. I can document Settings Catalog objects in English and German without issues. with an English OS.

I have to see if I can find a way to add some logging to this to identify the issue.

Do you have a computer with English OS and Word you can test on?

Cheers!

**Comment by UeliTri** [comment]
Hi,
Everything works fine on a new machine with EN-us and Word EN-us. 

Kind regards

[CloudAPIPowerShellManagement.log](https://github.com/user-attachments/files/16052581/CloudAPIPowerShellManagement.log)

**Comment by Micke-K** [comment]
Thank you for the update. I'll try to remember that next time the quest comes up :)

Cheers!
