### ISSUE TITLE
Unable to sign in: Error AADSTS700016

### ISSUE THREAD

**Issue by Cre3m5** [Micke-K/IntuneManagement#248]
Hi,

We receive the below error when we try to sign in with a global admin account.

"AADSTS700016: Application with identifier 'd1ddf0e4-d672-4dae-b554-9d5bdfd93547' was not found in the directory"

Seems like the default application (Intune Powershell) that is being used for the script is EOL. 

https://www.reddit.com/r/PowerShell/comments/1ctmiqy/msgraph_running_into_error_aadsts700016/

How can we fix this? 

By the way, we are currently still using version 3.9.0.

**Comment by Micke-K** [comment]
Hello,

You can change to Graph Module App in Settings. This is the default app from 3.9.6. 

Cheers!

**Comment by Cre3m5** [comment]
Many thanks for the quick reply and solution.
We didn't check the release notes earlier where it was mentioned.
