### ISSUE TITLE
Feature Request - Import Conditional Access: Enforce Disabled state

### ISSUE THREAD

**Issue by dotjesper** [Micke-K/IntuneManagement#25]
Hi,
Great project! This tools have soooo many features and nice additions, the Microsoft Endpoint Manager interface doesn't.

Have you considered an option to import Conditional Access Policies with: Enforce Disabled state?

I don't think I've missed anything in the documentation.

Thank you for your great work, very much appreciated!

**Comment by Micke-K** [comment]
Thank you!

I'll have a look at this. If it is missing, I'll add it.

**Comment by Micke-K** [comment]
Hello!

"Enforce Disabled state" - Do you mean setting the Enable Policy to Off? Or something completely different?

Or do you mean having a check box/drop down that can import Conditional Access polices with specified "Enabled policy" state?

**Comment by dotjesper** [comment]
Hello,
I was "dreaming", I will be able to export Conditional Access policies from one tenant, and then import them to another tenant, and as part of importing these Conditional Access policies ensure none of the will become active, ignoring the state they had during Export, "setting the Enable Policy to Off".

Thanks.

**Comment by Micke-K** [comment]
That should be possible. I'll have a look at it on the weekend.

**Comment by dotjesper** [comment]
Hello,
This new version (3.2.2) is super-awesome, and the way you implementer the import state og Conditional Access is pure magic - and it works quite well.

I will test further and let you know if any issues shows up.

Great work, thank you!

**Comment by Micke-K** [comment]
Thank you so much for the feedback, support and the kind words!
