### ISSUE TITLE
 Import Device Configurations

### ISSUE THREAD

**Issue by shabsn** [Micke-K/IntuneManagement#250]
Hey, I am trying to import Device Configurations from the Open Intune Baselines but I am getting this error:

![image](https://github.com/Micke-K/IntuneManagement/assets/173994324/edc84f6f-1019-4c62-87c9-ccdb9eeeeca0)

Can you maybe help with that?

Thank you :)

**Comment by Micke-K** [comment]
Hello,

I'm on holiday visiting family overseas at the moment.

I'll try to get some time to look at it while I'm here. 

Cheers!

**Comment by Micke-K** [comment]
Hello again,

I had a quick look at this. 
* I downloaded the zip from OpenIntuneBaseline and unzipped it. 
* Started the tool 
* Selected the Device Configuration item in the menu
* Clicked Import
* Browsed to the Device Configuration folder in the unzipped folder structure
* Verified that the "Win - OIB - Health Monitoring..." file was checked. 
* Clicked Import.

You have to be in the same menu item as the object you are trying to Import. I can replicate your issue if I select the "Device Configuration" in the menu but then try to import a json from the Settings Catalog. The script identifies the API to use based on the parent folder name.

This would explain why the name of the object is missing in your screenshot. 

Which file are you trying to import?

Cheers!

![image](https://github.com/Micke-K/IntuneManagement/assets/43226266/b6f79227-7f37-4b15-818d-5449781cd6fe)

**Comment by shabsn** [comment]
Seems like this solved my problems! Thank you so much!!!!
