### ISSUE TITLE
Missing a version column in the application overview

### ISSUE THREAD

**Issue by b0ndemand** [Micke-K/IntuneManagement#264]
Hi Mikael, thanks for the superb tool!

This is not really an issue, but more a request/wish. We have many applications (+300) in our many tenants (+25). 

One thing that would make it a lot easier for us to copy and move applications would be to have the version field added to the application overview (or maybe a way to add and remove columns?).  This way we will be able to tell the difference (without having to check the id).

Right now we have versions in the description field, but we are moving away from this, since our customers want a description with application information.

![Screenshot 2024-09-11 125121](https://github.com/user-attachments/assets/2131418c-f4eb-46f9-b8c9-3b88cda3b8cc)

**Comment by Micke-K** [comment]
Hello,

This is already possible. 
* Select a Win32 app in the list
* Click View 
* Select the Column tabs
* Add the properties you want to have in specified View
* You can change the header as well
* Click the Override default columns to override default
* Click Save
* Click the refresh to reload items with the new columns
 
![image](https://github.com/user-attachments/assets/9853bf9b-68a5-4bdc-8b23-f765e3f721c0)

![image](https://github.com/user-attachments/assets/dd2684ba-9f48-4eb2-9212-5758019c822f)

Cheers!

**Comment by b0ndemand** [comment]
Ah, so sorry! I was not aware of that function. Thank you!
