### ISSUE TITLE
Sort tenants by name

### ISSUE THREAD

**Issue by b0ndemand** [Micke-K/IntuneManagement#265]
Hi Mikael,

Another request and not a bug.

We have many tenants (+25), and they are all in the samer order, but it does not really make sense. It would be really nice if they could be sorted based on their name. You have a function for accounts in the settings, but i cannot see anything for the list of tenants. 

![image](https://github.com/user-attachments/assets/b5ed28e6-dcd9-42df-aad0-5c66712dc215)

It would be awesome to be able to sort all the tenants alphabetically.

thank you very much :-)

**Comment by Micke-K** [comment]
Hello,

I added a new option to sort the Tenant list. I can't try at the moment so let me know how it goes.

![image](https://github.com/user-attachments/assets/7fc88b14-db85-4166-ac3c-6d6033b0e882)

Cheers!

[MSALAuthentication.zip](https://github.com/user-attachments/files/16963484/MSALAuthentication.zip)

**Comment by b0ndemand** [comment]
I replaced the file, and logged in again. That did the trick. Thank you so much :-)
