### ISSUE TITLE
Export app with the same name

### ISSUE THREAD

**Issue by Oneill701** [Micke-K/IntuneManagement#266]
Hello,

We have several apps with the same name.
For exemple Google Chrome have the same name for iOS, Managed google play and for our Win32 apps.
And we have several win 32 apps with the same name. To manage several versions.

But when we export for a saving for exemple, it seems keep only one app with the same name.

Do you think it possible to manage this please? With an id for exemple.

**Comment by Micke-K** [comment]
Hello,

You can enable the "Add ID to export file" in Settings. This will make each file unique.

![image](https://github.com/user-attachments/assets/e936142d-d12e-4c7d-ab6f-2ba3086219ce)

Cheers!

**Comment by Oneill701** [comment]
Thanks.
Sorry for asking something existing. ;-)
