### ISSUE TITLE
Windows Hello Configuration

### ISSUE THREAD

**Issue by Roland0909** [Micke-K/IntuneManagement#271]
Hej Micke

Is it not possible to Export/Import "Windows Hello for Business" configuration und Windows enrollment?

Mvh
Roland

**Comment by Micke-K** [comment]
Hello,

Sorry, Windows Hello under Windows Enrollment is not supported. I might look at this in the future.

Cheers!

**Comment by Micke-K** [comment]
Closing this. This will be included if I get time to finish the next version.

Cheers!
