### ISSUE TITLE
Split method invocation failed when creating Word documents

### ISSUE THREAD

**Issue by ethanchal** [Micke-K/IntuneManagement#288]
Hello,

I'm trying to document our Intune policies using the Word option but the output file often shows an empty table for where the settings should be. The policy basics table appears fine every time.

This issue only occurs on certain policy types too e.g. OEMConfig, App Configuration. This issue doesn't happen with Device Configuration policies.

The CMD background prompt shows an error about the Split method missing on an PSCustomObject. Output below:

Any help would be much appreciated!

`Run PreProcess for Word`
`Filter:`
`Loading Android-AppConf-MgdHomeScreen-Shared`
`Get documentation info for Android-AppConf-MgdHomeScreen-Shared (App Configuration (Device))`
`Run NewObjectGroup for Word`
`Run NewObjectType for Word`
`Process Android-AppConf-MgdHomeScreen-Shared (App Configuration (Device)) - Word`
`Could not find string Name ValueType Value. Part 'Name' was not found`
`Failed to process object Android-AppConf-MgdHomeScreen-Shared Exception: Method invocation failed because [System.Management.Automation.PSCustomObject] does not contain a method named 'Split'.`
`Run PostProcess for Word`
`Document C:\Users\ecadmin\Desktop\Documents\xxx\test.docx saved successfully`

**Comment by Micke-K** [comment]
Hello,

Do you get the same issue if you document one of those polices in HTML?

Cheers!

**Comment by ethanchal** [comment]
Hello, thanks for getting back to me so soon.

Documenting in HTML mode works fine, the settings table appears as expected.

Here are my output settings for Word:

![image](https://github.com/user-attachments/assets/0e9529c0-4c80-494f-ad92-0efadcc6cd0a)

![image](https://github.com/user-attachments/assets/9d1bce56-5b6c-401b-831f-25b5cb7bd6e1)

![image](https://github.com/user-attachments/assets/a15d5092-e11e-4d11-8d59-0953e44c5aa5)

**Comment by ethanchal** [comment]
Another note to say that after checking HTML mode, I tried Markdown and the Split error appears on this output type too.

**Comment by Micke-K** [comment]
Hello,

I could finally reproduce and hopefully fix the issue.

Can you test the attached files, Word and MD.

Cheers!

[DocumentationMD.zip](https://github.com/user-attachments/files/18148427/DocumentationMD.zip)

**Comment by ethanchal** [comment]
Hey!

Fantastic, the updated files worked for me, thank you so much! Really appreciate your efforts to this project.
