### ISSUE TITLE
Custom OMA-URI values encrypted after export/import

### ISSUE THREAD

**Issue by easyngit** [Micke-K/IntuneManagement#29]
Hi,

We have been seeing a weird issue after we have done an export and import to a tenant. All values from what we can tell get set as encrypted and all we see in the values is "***"

![Chrome-failure](https://user-images.githubusercontent.com/23801363/135090075-f988bc9b-d711-45e9-8914-f82bcbc62d89.jpg)

![Chrome-EncrypedValues](https://user-images.githubusercontent.com/23801363/135089747-501ac69c-fa74-4967-a0c7-ae766fdfca1b.jpg)

We discovered this issue first time when we tried to import some policies for Google Chrome. But we have also seen this happening to our ADMX OMA-URI policy for Lenovo Commercial Vantage.
So far the only solution we have found is to manually recreate the values that get encrypted. 

Edit: This has happened around 4 times the last 2 months.

**Comment by easyngit** [comment]
A workaround to this issue has been to click view on a file and click "Load Full" before doing the export. Seems like there is an issue with the secret during export.

**Comment by Micke-K** [comment]
Hello!

Thank you for reporting this. The secret values was something Microsoft introduced a few months ago. Strings are now stored as encrypted in Intune but support for this was implemented in a previous version.

I cannot replicate the issue with the latest version. I exported a Custom OMA-URI for Chrome. If I look at values without loading the Full View, value is ***** but in the exported file it is the actual string. I did NOT loaded the full value before export. I also did a Bulk Exporting of all Device Configuration profiles directly after I started the app and the actual strings values were exported. 

What versions of EndpointManager.psm1 and MSGraph.ps1 do you have? Versions are available in About. It should be 3.1.11 and 3.1.6.

Note that the json files must be re-exported to get the decrypted strings in the json. Exported files with ***** values cannot be decrypted after export.

**Comment by retsak** [comment]
This can be easily solved with converting the secret reference value, for example:

$json.omaSettings | ForEach-Object { ​​​​​​​
    $secretReferenceValueId = $_.secretReferenceValueId
    $isEncrypted = $_.isEncrypted
    <# Example to convert:
            https://graph.microsoft.com/beta/deviceManagement/deviceConfigurations/
            76298dc2-1f4e-43d3-a157-c43696f0ae12/
            getOmaSettingPlainTextValue
            (secretReferenceValueId='76298dc2-1f4e-43d3-a157-c43696f0ae12_815ad3e3-76298dc2-1f4e-43d3-a157-c43696f0ae12_76298dc2-1f4e-43d3-a157-c43696f0ae12')
        #>
    if ($isEncrypted) {
        ​​​​​​​
        $secretReferenceValueId
        $uri = "https://graph.microsoft.com/beta/deviceManagement/deviceConfigurations/$policyID/getOmaSettingPlainTextValue(secretReferenceValueId='$secretReferenceValueId')"
        $result = Invoke-RestMethod -Method Get -Uri $uri -Headers $authToken
        $_.secretReferenceValueId = $null
        $_.isEncrypted = $false
        $_.value = $result.value
    }​​​​​​​
}​​​​​​​

**Comment by Micke-K** [comment]
This is taken care of by the Start-PostGetDeviceConfiguration function in the EndpointManager.psm1 file. This function is called every time the full Device Configuration object is loaded e.g. View Full Object, Export Object, Document Object etc.

![image](https://user-images.githubusercontent.com/43226266/135185008-b98deda2-c66b-4a74-9e5c-fdcd483397f5.png)

**Comment by Micke-K** [comment]
@easyngit Any update on this? Did you try re-export the profiles with the new version?

**Comment by easyngit** [comment]
@Micke-K Sorry for the late reply im away from work untill monday so will discuss this with my colleague then. If you want we can just close this issue now. Thanks for taking time responding! This is a great tool.

**Comment by Micke-K** [comment]
No problem and thank you!
I'll close it when you have verified that it working. 

Cheers!

**Comment by easyngit** [comment]
Hi Micke!

Sorry for the delayed response, we have been discussing this error this week and been trying to find out why this is happening. We have seen the error multiple times in our OMA URI policies but we have so far been unsuccessful in finding the culprit of why they don't retain their secret when exporting directly from the view without pressing View --> Load Full first. 

I have created a meeting for tomorow with my colleague where we will try to troubleshoot further. Will come back to you tomorow.

**Comment by Micke-K** [comment]
I'm not sure if I misunderstood your problem. The values for OMA-URI will always be ***** when you view details and then visible when you load the full object. The full object is loaded during export so clear text values will be included in the export. 

This is because Microsoft encrypts the strings and the API returns *****  when objects are loaded. A second API is required to decrypt the string. This is only called when loading the full object.
