### ISSUE TITLE
Feature request: Save settings in json file, allowing to roam settings

### ISSUE THREAD

**Issue by dotjesper** [Micke-K/IntuneManagement#33]
Hi,

This might a minor issues, however I most often (always'ish) run the IntuneManagement tool from within Windows Sandbox, as I do not want to have any "foreign" sign in information on my own computer, and I feel good about closing Windows Sandbox, and everything is cleared.

Have you considered, to add an option or a command line option to save settings to a file, e.g. a json file, allowing the setting to roam between devices and/or be saved when e.g. using Windows Sandbox environment or similar?

Thank you, this is, IMHO, the best Intune Management "extension" out there, keep up the good work!

PS: Sorry for keep throwing feature request you way :)

**Comment by Micke-K** [comment]
Thank you so much for all these feature requests. Please, don't stop. You have lots of great ideas. 

This is a really great idea. I have a few plans for managing settings information  a bit different compared to what it is today. 

I could probably solve this in a very simple way eg export/import settings as a first stage but I'll see what I can cone up with. One idea I have is to have tenant specific settings. Anything that is not configured for the tenant will get the "global" settings.

**Comment by Micke-K** [comment]
I've added this in the latest master branch release. You can now export setting to a json and used that as settings and then copy it to other devices. Have a look at the README on how to do this. Let me know if you have any questions!

Thank you for the kind words and all the support!

**Comment by Micke-K** [comment]
Can we close this now?

**Comment by Micke-K** [comment]
Closing this. 
 
Please open an new issue if it is nor working. 

Cheers!
