### ISSUE TITLE
Feature Request : Documentation - Extract powershell scripts

### ISSUE THREAD

**Issue by HornEman71** [Micke-K/IntuneManagement#34]
Hi,

I must echo @dotjesper thoughts on this! Its absolutely brillant and has saved a lot of time with cloning configuration policies, especially as the offical Microsoft Intune powershell module is not up to date and fails cloning configurations.   Keep up the fantastic work!

Feature Request: Is it possible to extract the various powershell scripts and document those? e.g. install and uninstall scripts aswell as any custom detection scripts? etc  I know files etc are encrypted and then decrypted on the device so not sure if this is possible,   It would certainly make the documentation process more complete.

Many thanks Justin

**Comment by Micke-K** [comment]
Closing this since it is not possible. 

Cheers!
