### ISSUE TITLE
Load Settings from json

### ISSUE THREAD

**Issue by martincaddick** [Micke-K/IntuneManagement#37]
Looking further at documentation. On the jumpbox (without word) I can export the configuration to all the json files and then copy to a workstation (that does have word installed). If it were possible to 'Load' the configuration (without importing) and then document from the loaded configuration, that would be awesome.

Cheers

**Comment by Micke-K** [comment]
Hello!

This should be possible. I kind of do this already in the Compare feature when using the documentation provider. I'll look into this. 

Cheers

**Comment by Micke-K** [comment]
The lates upload has support for documentation based on exported files. 

Try it out when you have time. 

Please note that some properties will not be documented if it can't connect to the tenant. These are referenced values like root certificate on SCEP profiles and certificate on VPN profiles. 

Cheers!

**Comment by martincaddick** [comment]
Noticed the new version yesterday and have already been testing. Jumpbox doesn't have word and does export correctly. Copied source to workstation that has Word installed and started documenting. Only issue I can see (specific to the environment) is that I am unable to use the proxy via PowerShell (constrained language mode) and therefore fails when using graph to enumerate groups / membership so I end up with a lot of guids in the doc rather than names.
Different tenant worked fine. CPU stayed at about 20-40% while generating the doc which took about 15 minutes and produced 280 pages. Let's call it a win. Nice job!

**Comment by Micke-K** [comment]
Did you copy the migration table? The group name should be translated correctly if the MigratioTable.json is there. I documented an environment from export while logged into another and I got the group names. 

Cheers!

**Comment by martincaddick** [comment]
I've been running cmtrace with the log file in debug and I can see it trying to connect to graph.microsoft.com for things like servicePrincipals, directoryObjects, namedLocations and directoryRoleTemplates

**Comment by Micke-K** [comment]
I'm so sorry looks like I completely missed to reply to this. 

I realised that there are quite a lot of dependencies that it tries to load even during offline documentation. I am looking into this right now. I've fixed a few of them. 

Not sure about completely offline documentation. Then I need to add a lot of things into the MigTable. When I do offline documentation, I'm logged in to another tenant so I can still get some info from Graph. Can you do that or do you need absolutely no Internet access for the documentation?

I'll have a look at the additional settings. Should be possible. 

Cheers!

**Comment by martincaddick** [comment]
np. I managed to email the config out to then run the doco on another tenant (when I excluded the scripts that were blocked)

**Comment by Micke-K** [comment]
Additional offline documentation support added in 3.5.0

Please report any issues to this thread

**Comment by Micke-K** [comment]
> This change has already made a huge difference. If they're easy to implement a couple of extras would be:
> selectable style for table captions and table text
> selectable for table caption above or below the table

This is included in 3.5.0. Let me know if you think it is ok

**Comment by Micke-K** [comment]
Closing this. It's been implemented since 3.5. 

Please open a new Issue if you have any problems. 

Cheers!
