### ISSUE TITLE
Import is not working

### ISSUE THREAD

**Issue by mahybabu** [Micke-K/IntuneManagement#4]
I got the below error message, while importing the configuration profile using this tool.
I tried one by one and a bulk import option but its not working. Export is working fine.
Even I tried to copy a configuration profile, it failed.

Can you please fix this.

Failed to invoke MSGraphRequest Exception: 400 Bad Request
{
  "error": {
    "code": "ModelValidationFailure",
    "message": "Cannot convert the literal '/Date(1571240587193)/' to the expected type 'Edm.DateTimeOffset'.",
    "innerError": {
      "message": "Cannot convert the literal '/Date(1571240587193)/' to the expected type 'Edm.DateTimeOffset'.",
      "request-id": "f173776b-a770-4a1e-a948-967b4a630684",
      "date": "2020-04-08T15:02:26"
    }
  }
}

**Comment by RogerHaugen** [comment]
I also get this error now

**Comment by mdcaddic** [comment]
Currently working on this. It is the date format that is incorrect and the majority of the extensions push the createdDateTime and lastModifiedDateTime on import. These are not required and it's relativity easy to comment those out.

**Comment by RogerHaugen** [comment]
Yeah, had to comment out all those before import.

**Comment by mdcaddic** [comment]
Roger,
Wanting to make the minimum changes I've done a mix of filtering to remove the offending objects or removing the object properties depending on what the functions were already doing. Are you going to do a pull and update the repo?

[Intune Export - Import Fixes.docx](https://github.com/Micke-K/IntuneManagement/files/4497787/Intune.Export.-.Import.Fixes.docx)

**Comment by mahybabu** [comment]
> Roger,
> Wanting to make the minimum changes I've done a mix of filtering to remove the offending objects or removing the object properties depending on what the functions were already doing. Are you going to do a pull and update the repo?
> 
> [Intune Export - Import Fixes.docx](https://github.com/Micke-K/IntuneManagement/files/4497787/Intune.Export.-.Import.Fixes.docx)

**Comment by mahybabu** [comment]
> > Roger,
> > Wanting to make the minimum changes I've done a mix of filtering to remove the offending objects or removing the object properties depending on what the functions were already doing. Are you going to do a pull and update the repo?
> > [Intune Export - Import Fixes.docx](https://github.com/Micke-K/IntuneManagement/files/4497787/Intune.Export.-.Import.Fixes.docx)

Great, Thanks for sharing.

**Comment by RogerHaugen** [comment]
> Roger,
> Wanting to make the minimum changes I've done a mix of filtering to remove the offending objects or removing the object properties depending on what the functions were already doing. Are you going to do a pull and update the repo?
> 
> [Intune Export - Import Fixes.docx](https://github.com/Micke-K/IntuneManagement/files/4497787/Intune.Export.-.Import.Fixes.docx)

No sorry, i meant that i had to comment out the date properties in all my json files, to be able to import them

**Comment by Micke-K** [comment]
Hello! 
I am so sorry for not been replying...I actually forgot about this and I never got an email notifications to remind me.
I've not been working with Intune for almost a year. Been very busy with Azure... 
A huge thank to @RogerHaugen for helping out!

Does anyone want to join this project as contributor? I have lots of additional ideas for this project but so little time. I need more people helping out if there is still an interest in this!

Cheers!

**Comment by Taurus-Dev** [comment]
Hello
Just tried the copy function in the Device configurations and i'm getting the same error message as stated before. I checked the files and cannot find the CreatedDate function in the code. Any suggestions?

Thanks!

**Comment by Micke-K** [comment]
Taurus-Dev: I'll have a look at this. I have an idea how to fix this. I'll try to get time to do it this week

**Comment by Taurus-Dev** [comment]
> Taurus-Dev: I'll have a look at this. I have an idea how to fix this. I'll try to get time to do it this week

Thanks for taking the time!

**Comment by Micke-K** [comment]
Try the latest version and let me know how it goes.

Please see change log in the readme (support for AzureRM is removed. Az module is new dependency)

**Comment by Taurus-Dev** [comment]
> Try the latest version and let me know how it goes.
> 
> Please see change log in the readme (support for AzureRM is removed. Az module is new dependency)

Works like a charm, tested the copy function on several sections with success. Hopefully the Intune team will implement these functions as default as it's basic functionality. Thanks a bunch!

**Comment by Micke-K** [comment]
Fixed in version 2

Thank you Taurus-Dev for verifying!
