### ISSUE TITLE
deviceEnrollmentConfigurations filter not accepted by microsoft graph api

### ISSUE THREAD

**Issue by illuvtar** [Micke-K/IntuneManagement#41]
Query:https://graph.microsoft.com/BETA/deviceManagement/deviceEnrollmentConfigurations?$filter=not endsWith(id,'Windows10EnrollmentCompletionPageConfiguration')
Status code: InternalServerError

Graph is not accepting filter containing endswith for deviceEnrollmentConfigurations, this is impacting 'Enrollment Restriction' and 'Enrollment Status Page', same result with graph explorer.

This seems to be a recent issue, I have not been able to locate an impacting change in https://developer.microsoft.com/en-us/graph/changelog/ 

Thanks for your work.

**Comment by Micke-K** [comment]
Thank you for reporting this and for the support!

I'll look into into later today or tomorrow. I have a few changes that is coming soon and I hope to fix it next upload. 

Cheers!

**Comment by Micke-K** [comment]
Hello!

I've identified the issue and fixed it locally. It fixed a few other minor things as well that I didn't know was broken. 

I'm testing other changes and I'll uploadas the updates as soon as they are verified. Hopefully this or next week. 

Cheers!

**Comment by Micke-K** [comment]
Download the latest version and test it when you have time. This should be working now. 

Cheers!

**Comment by illuvtar** [comment]
Yes, 'Enrollment Restriction' and 'Enrollment Status Page' are both working as expected.
Love the new features in the current release.

Thanks
