### ISSUE TITLE
Copy application not working

### ISSUE THREAD

**Issue by ncheymol** [Micke-K/IntuneManagement#42]
the functionality to copy application doesn't download and upload the app content. 

The application created is unusable : 
Your app is not ready yet. If app content is uploading, wait for it to finish. If app content is not uploading, try creating the app again.

**Comment by Micke-K** [comment]
Hello!

That is by design at the moment. The core thing here is that Microsoft does not allow to export content. So copy will not work. 

I'll have a look and see if I can do the same as for import. It would then upload the file if it is found locally. 

Cheers!

**Comment by ncheymol** [comment]
If you can add a popup to go select the file or the folder locally it would be a good work around

**Comment by Micke-K** [comment]
This is fixed in the latest update. 

Please test and see if it works the way you expect it to. 

Cheers!

**Comment by ncheymol** [comment]
It's working, thanks
