### ISSUE TITLE
Generalise JSON files

### ISSUE THREAD

**Issue by dridley23** [Micke-K/IntuneManagement#45]
Is it possible to strip out the ID, Created Date, Modified Date of the JSON files that are exported please?

**Comment by Micke-K** [comment]
Hello!

Removing this could break the import. Dependencies between policies will be broken. Replacing all id's with new ones would require a redesign of the export functionality. 

I can look into this a bit for a future release but you should expect some imports to fail or be missing sone settings. 

Cheers!

**Comment by dridley23** [comment]
This issue arose because in some accounts we feel we would be able to use this tool to BACKUP. However, the concern is around getting approval to use it for IMPORT.
I assume there is no reliance on this tool to import files backed up from it.
But from experience, if importing JSON files via graph, it fails because these fields are in the JSON file.

So for sensitive accounts that don't allow use of this tool for import, is it just a matter of finding the relevant Psh cmdlet to import? Does it actually use graph for any imports?

**Comment by Micke-K** [comment]
It uses Graph for everything. There are no Microsoft PowerShell modules involved. 

If you want to import a generalised json with a MS module it would end up using an API call. You would call the Graph API for the object type you are importing and include the json as the content for the post operation. Technically, it will be exactly the same as using the tool. The only difference is that you call eg Invoke-GraphRequest in a Microsoft PS module. 

Cheers!
