### ISSUE TITLE
Kiosk Template Policy - Documentation

### ISSUE THREAD

**Issue by dridley23** [Micke-K/IntuneManagement#49]
Hi Micke,

I noticed documentation of kiosk template doesn't document the kiosk profile settings within it. Instead it just shows the text "Policy;"
See attacchment.

Cheers.

![image](https://user-images.githubusercontent.com/95395320/173344262-cf04c6bf-45e7-4e7b-b0d0-550823ada541.png)

**Comment by Micke-K** [comment]
I'll have to do some custom settings for the Kiosk documentation.

**Comment by dridley23** [comment]
Great progress Micke with updated Core version. Profile now shows but "User Type" is blank (for AAD group anyway)...


![image](https://user-images.githubusercontent.com/95395320/176079548-9660a6c1-8932-4142-b6d4-1260c79935df.png)

![image](https://user-images.githubusercontent.com/95395320/176079754-c35a4864-003d-4b8f-a2db-3cb819f92646.png)

**Comment by dridley23** [comment]
This is now fixed in v3.6.0
Thanks @Micke-K
