### ISSUE TITLE
Device Type Restriction - Documentation

### ISSUE THREAD

**Issue by dridley23** [Micke-K/IntuneManagement#54]
Hi Micke - Device Platform Restrictions (and Default Device Limit Restrictions) pull the wrong default assignment.

Portal:
![image](https://user-images.githubusercontent.com/95395320/173994805-c0294d9c-7b67-489f-9f59-5ff4002bf77d.png)

Doco:
![image](https://user-images.githubusercontent.com/95395320/173994972-475452a8-73ba-48ab-890b-61a73556e0b0.png)

**Comment by Micke-K** [comment]
This was a bad one. They were swapped around. Also found a bug where assignments were missing for some Device Configuration profiles. Microsoft added a property on the assignment object which broke it earlier this year.
Both will be fixed in next release

**Comment by dridley23** [comment]
Thanks. Confirmed fixed in v3.5.1 (Core & MSALAuthentication)
