### ISSUE TITLE
Device Control (EPS) template - Documentation

### ISSUE THREAD

**Issue by dridley23** [Micke-K/IntuneManagement#59]
Hi @Micke-K 

New one for you...
Doco does not capture all the Device Control template policies defined in 'Endpoint Security \ ASR' blade.
To reproduce, define all settings including block list.

**Comment by Micke-K** [comment]
This should be fixed in the latest release (3.6.0)

**Comment by dridley23** [comment]
Yep confirmed fixed. Thanks @Micke-K
