### ISSUE TITLE
Unable to import software update settings

### ISSUE THREAD

**Issue by durrante** [Micke-K/IntuneManagement#6]
Hello,

Appears to be the same issue as previous when importing conifguration items (date \ time), I've followed the fixes docx but the issue persists with the software update configuration items, I assume it's due to the following fields in the SU config json files:

"qualityUpdatesPauseExpiryDateTime":  "\/Date(-62135596800000)\/",
    "featureUpdatesPauseExpiryDateTime":  "\/Date(-62135596800000)\/",
    "qualityUpdatesRollbackStartDateTime":  "\/Date(-62135596800000)\/",
    "featureUpdatesRollbackStartDateTime":  "\/Date(-62135596800000)\/",

I have resolved this by updating the ConfigurationItems.psm1 file and adding in the above items into line 217 so the line should read:

Invoke-GraphRequest -Url "/deviceManagement/deviceConfigurations" -Content (ConvertTo-Json ($obj | Select-Object -Property * -ExcludeProperty createdDateTime, lastModifiedDateTime, qualityUpdatesPauseExpiryDateTime, featureUpdatesPauseExpiryDateTime, qualityUpdatesRollbackStartDateTime, featureUpdatesRollbackStartDateTime) -Depth 5) -HttpMethod POST

Hope this helps

**Comment by Micke-K** [comment]
Fixed in version 2
