### ISSUE TITLE
Compliance Policy export/import

### ISSUE THREAD

**Issue by dridley23** [Micke-K/IntuneManagement#60]
Hi @Micke-K,

Compliance policies don't seem to be exporting/importing the custom scripts (PS1 & JSON), and you can't modify the policy after importing it.

**Comment by Micke-K** [comment]
I added support for the Compliance Scripts object + documenting Custom settings in the compliance object.
I uploaded new files to my shared folder for you to test. Copy psm1 files to Extensions and Strings-en.json to documentation. Let me know how it goes.

**Comment by dridley23** [comment]
Nice one @Micke-K ...It works **BUT** i had to import the psh script first, so is it possible that if just the compliance policy is imported, it checks for the psh dependency and imports that first?
I assume the ImportOrder would take care of this for Bulk import?

**Comment by Micke-K** [comment]
I did add the dependency for it in the script. Did you select both during bulk import?
Dependency/import order does not force import of dependency objects. You have to select it in bulk import or pre-import dependency when importing single objects.
