### ISSUE TITLE
Excessive AAD groups created when importing policy Assignments

### ISSUE THREAD

**Issue by dridley23** [Micke-K/IntuneManagement#62]
Hi @Micke-K ,

This might also fall under a feature request too, but i find when i import individual policies (and selecting import assignments) that it creates all AAD groups from the export folder, not just the ones assigned to that policy.

**Comment by Micke-K** [comment]
The export will only include groups that is used in assignments so it should be the group to import as well, unless you import them one by one.

I do agree it is a bit annoying that it imports all the groups. I'll see if I can redesign the whole group Import/Export process. Might not be in the next release though.

**Comment by dridley23** [comment]
Sounds great! Yeah it was the single imports i was referring to thanks.
Love ya work...
