### ISSUE TITLE
Feature Request: Window/GUI Colour scheme per tenant

### ISSUE THREAD

**Issue by dridley23** [Micke-K/IntuneManagement#63]
Hi @Micke-K  - Thinking it would be great if we could set a per tenant windows colour scheme and/or place the Tenant name at the top of the window. I work on a lot of tenants, switching between them but they all look the same.
It would be great to have the Tenant name at the top as a constant reminder of which tenant i'm attached to. Plus a colour scheme so i could set the Production tenant to RED (for example) to remind me to extra careful.

**Comment by Micke-K** [comment]
Haha. I've been think about the exact same thing for a long time. I even looked at it once but it was not easy to change the colour of the Window title background so I gave up. 

I'll give you a call and we can discuss different options.

**Comment by dridley23** [comment]
Yeah i am trying to idiot-proof myself. 👍

**Comment by dridley23** [comment]
New files you provided has successfully added Tenant name to menu banner + i am able to change the menu banner colour which is AWESOME. Any chance you can add ability to change the menu font colour though (as it is hard to see on dark colour backgrounds)?

**Comment by dridley23** [comment]
Font colour works too with new files! Wayyyyyyyyyyyyyyy better now!
