### ISSUE TITLE
Exported App Protection Policy Targeted App settings do not follow export tenant

### ISSUE THREAD

**Issue by SkipToTheEndpoint** [Micke-K/IntuneManagement#67]
If I configure an App Protection Policy with a "Target policy to" and choose either All Apps, All Microsoft Apps, or Core Microsoft Apps and export that policy, when imported into another tenant, the resultant import individually defines each public app that existed in the setting when it was exported rather than the collection.

The following lines in the json seem to suggest the app collections logically exist:
`"appGroupType@odata.type":  "#microsoft.graph.targetedManagedAppGroupType",
"appGroupType":  "allMicrosoftApps",`

**Comment by Micke-K** [comment]
Thank you for reporting this
I found the issue. It will be fixed in the next release

**Comment by Micke-K** [comment]
This should be fix in 3.7.0. 

Let me know if get the chance to test it. 

Cheers

**Comment by SkipToTheEndpoint** [comment]
Tested with version 3.7.0 for both Android and iOS and the import now respects the exported settings.

Thank you!
