### ISSUE TITLE
App Protection doesn't process any WIP policies

### ISSUE THREAD

**Issue by Stuclark75** [Micke-K/IntuneManagement#7]
The App Protection / Configuration section works fine for Android and iOS app policies, but doesn't do anything (can't view, export, copy, import) with Windows Information Protection Policies.

I have ascertained that this is because they are named differently in PS - rather than managedAppProtection they are windowsInformationProtection policies.

Can someone who knows Powershell better than me add in the ability to manipulate these policies?

**Comment by Micke-K** [comment]
Fixed in version 2
