### ISSUE TITLE
Documentation - Writes into open word documents

### ISSUE THREAD

**Issue by dridley23** [Micke-K/IntuneManagement#71]
Hi - I hit a weird issue today. I was running "Document" feature but while it was running i opened Word to work on a completely unrelated document. I noticed it started inserting content into this external document of mine.

Note: I am not sure if it is because i was using a custom work template, which was also the template used in the document i had open. Plus it is hard for me to reproduce but it has happened more than once.

Any ideas? Thanks.

**Comment by Micke-K** [comment]
Hey!

I've had a couple looks at this but I can't replicate it. Ping me and let me know how you managed to do this :)

Cheers!

**Comment by Micke-K** [comment]
Hello David!
Could you ever reproduce this? Or can we close it?
Cheers!

**Comment by dridley23** [comment]
No, i could not reproduce this, but i had seen this multiple times in the past. I wonder if recent updates since then have somehow resolved it. Not sure...happy to close for now.
