### ISSUE TITLE
Windows Autopilot profiles not visible anymore

### ISSUE THREAD

**Issue by Yomodo** [Micke-K/IntuneManagement#74]
Thank you for this great tool!

To verify: In my tenant I can see all Windows Autopilot profiles but using your
(excellent!) tool I see none, only the two defaults policies:

![image](https://user-images.githubusercontent.com/10358198/182031820-f67ace23-d27c-4426-8647-e68af7bc768b.png)

All other types of policies show-up as expected.
Can perhaps someone confirm this?

**Comment by Micke-K** [comment]
Hello!

Thank you for the kind words!

Windows Autopilot policies is under the Autopilot node. Enrollment Restrictions is only for restriction policies, Device Limit and Device Type.

Each node uses one API so that's why it's not a one to one mapping with the portal. 

Cheers!

**Comment by Yomodo** [comment]
Hm, not sure how I missed that Autopilot node.
Unfortunately, this one is also empty, clicking on "Load All" and/or "Load More" yields no results.

**Comment by Micke-K** [comment]
I've tested a couple of versions and different environments. I always get the available Autopilot profiles in the list.

Any hint in the log? If not, what if you enable debug logging in settings?

Cheers!

**Comment by Yomodo** [comment]
> I've tested a couple of versions and different environments. I always get the available Autopilot profiles in the list.

Oke, that's what I need, some kind of confirmation that it works, I even went down the C# route, to no avail
so clearly my problem lies elsewhere.

I will close this, thank you for your awesome work and swift response!

Cheers!
