### ISSUE TITLE
Menu bar is empty in 3.7.0 (labels missing)

### ISSUE THREAD

**Issue by SasStu** [Micke-K/IntuneManagement#78]
The menu bar entries are all empty when I start 3.7.0. In version 3.6.0 it still works.
![image](https://user-images.githubusercontent.com/28406607/183411868-fb3c1401-2e60-40b4-af2b-df07017d6d56.png)

The console shows an error message
![image](https://user-images.githubusercontent.com/28406607/183412256-66e3cc22-fb5b-4fe4-8440-82ed6aea79b7.png)

Thanks for the great tool!

**Comment by Micke-K** [comment]
Bug caused when not logged in.

Fixed in 3.7.1

Cheers!

**Comment by SasStu** [comment]
Thank you for the quick fix! Works like a charm but it seems that the update checker does not recognize the new version
![image](https://user-images.githubusercontent.com/28406607/183450678-9df31880-2237-4200-b2f2-dadd2e63ad42.png)

**Comment by Micke-K** [comment]
Sorry, This should be fixed now. 

I named the release wrong on GitHub. I was a bit too tired.

Cheers!

**Comment by Micke-K** [comment]
Closing this. Fixed in the latest release. 

Cheers!
