### ISSUE TITLE
GitHub version and local version missmatch

### ISSUE THREAD

**Issue by edthefixer** [Micke-K/IntuneManagement#79]
First of, fantastic tool! always use it.
For some reason now when launching "Start-IntuneManagement.ps1"in either ISE or VSCode does not load anymore (version 3.7.1) and I get this error message:

Local version: 3.7.1
GitHub version: 3.71
OK

Tried to look into the code to see if I can find the 3.71 reference and did not find it.... suggestions?

Ed

**Comment by Micke-K** [comment]
Hello!

Sorry that was me being tired and did an emergency release late at name and named it wrong on GitHub.

The tool compares the Release in local files with the latest release version on GitHub.

Fixed now.

Thank you so much for reporting.

Cheers!

**Comment by edthefixer** [comment]
Mikel,

No, thank you! I really appreciate your work!

Thanks

Ed
________________________________

**Comment by Micke-K** [comment]
Closing this since it is fixed. 

Cheers!
