### ISSUE TITLE
Silent Batch Job Certificate Issue

### ISSUE THREAD

**Issue by cstaubli** [Micke-K/IntuneManagement#85]
I tried to setup a CI Pipeline with silent mode and certificate authentication, but was unable to. With secret authentication everything works as desired. After some debugging I've found the following issue:

The method Microsoft.Identity.Client.ConfidentialClientApplicationBuilder WithCertificate expects a value of type [X509Certificate2](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate2) rather than a string as defined in [Start-IntuneManagement.ps1](https://github.com/Micke-K/IntuneManagement/blob/master/Start-IntuneManagement.ps1#L19) and [CloudAPIPowerShellManagement.psm1](https://github.com/Micke-K/IntuneManagement/blob/master/CloudAPIPowerShellManagement.psm1#L87) ([Source](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.confidentialclientapplicationbuilder.withcertificate?view=azure-dotnet#microsoft-identity-client-confidentialclientapplicationbuilder-withcertificate(system-security-cryptography-x509certificates-x509certificate2))). The method in question is located in [MSALAuthentication.psm1](https://github.com/Micke-K/IntuneManagement/blob/master/Extensions/MSALAuthentication.psm1#L576)

Changing the param type to X509Certificate2 fixed the authentication with certificate for me, I fetch a certificate from LocalMachine store and pass this to the parameter Certificate, like this

```powershell
$f = [System.Security.Cryptography.X509Certificates.OpenFlags]::ReadOnly

$store = New-Object System.Security.Cryptography.X509Certificates.X509Store("My", "LocalMachine")

$null = $store.Open($f)

$cert = $store.Certificates | Where-Object {$_.Subject -eq "..."}

$TenantId = "..."

$AppId = "..."

$SilentBatchFile = "BulkExport.json"

.\intunemanagement\Start-IntuneManagement.ps1 -Silent -TenantId $TenantId -AppId $AppId -SilentBatchFile $SilentBatchFile -Certificate $cert

$null = $store.Close()
```

If you prefer I can submit a PR with these changes

**Comment by Micke-K** [comment]
Hello Christian,

Great find!

The question is where it is better to convert it to a cert. That should probably happen where it is actually used and not in the start script. 

Can you get it to work if you implement it in the function in the MSALAuthenication.psm1 file instead? I'm happy to approve a PR if you get that to work. 

Thank you!

Cheers!

**Comment by cstaubli** [comment]
Hi Mikael

Sure I can change it in MSALAuthenication.psm1 and convert the thumbprint provided to a X509Certificate2. I propose to search in LocalMachine store for a certificate, what do you think?

Cheers
Christian

**Comment by Micke-K** [comment]
We can start there. Next option would be to check User store if not found in the machine store. 

Thank you so much!

Cheers!

**Comment by cstaubli** [comment]
I've created a PR, which checks both LocalMachine and CurrentUser store

**Comment by Micke-K** [comment]
Closing this since the PR is merged

Cheers!
