### ISSUE TITLE
App Protection Policy Import

### ISSUE THREAD

**Issue by Arne-RFA** [Micke-K/IntuneManagement#9]
App Protection Policies, it looks as this issue was resolved here https://github.com/AlwaysLearningTech/IntuneManagement/commit/ef3bd7ccb5f8f09ae7f4efda4513d9aa672b1cd0

**Comment by Arne-RFA** [comment]
I created a pull request with the merged fixes from above https://github.com/Micke-K/IntuneManagement/pull/10

**Comment by Micke-K** [comment]
The Start-PreImport already removes lastModifiedDateTime','createdDateTime','supportsScopeTags','id' so you don't have to remove them again
So only the last change (for assignments) would be required. But it is better to call Start-PreImport to make sure it removes all properties to ignore

Can you try that?

**Comment by Arne-RFA** [comment]
new PR created with just the MSGraph change https://github.com/Micke-K/IntuneManagement/pull/11

**Comment by Micke-K** [comment]
Version 3 Beta 1 released - Complete rewrite. Issues fixed
