### ISSUE TITLE
Problem loading Application .json files

### ISSUE THREAD

**Issue by Nordstrom96** [Micke-K/IntuneManagement#92]
Currently having a problem to import some of my .json in the "application" tab.
I got 2: 1 for Microsoft Edge and 1 for Office apps. It has worked for the past 2 years, but today it seems to be stuck at "Loading applications object".

Gettiing this error:
Failed to invoke MS Graph with URL https://graph.microsoft.com/beta/deviceAppManagement/mobileApps (Request ID:XXX). Status code: BadRequest

Any solution to this?

**Comment by Micke-K** [comment]
Hello!

Can you attach one or both the apps so I can test. 

Are they Win32 apps?

Did you export them recently or are they old exports?

Cheers!

**Comment by Nordstrom96** [comment]
Hello there Mikael,

It is these two.
They worked fine 1 week ago.
The Edge one is set up as this:
[cid:ec1988b7-7a13-4657-bd1c-22683cbdfed5]
And the Office one is set up like this:
[cid:b6c06c7d-cc95-4d6e-817e-c43b023e2bf6]
________________________________
Fra: Mikael Karlsson ***@***.***>
Sendt: onsdag 28. september 2022 14:37
Til: Micke-K/IntuneManagement ***@***.***>
Kopi: Nordstrom96 ***@***.***>; Author ***@***.***>
Emne: Re: [Micke-K/IntuneManagement] Problem loading Application .json files (Issue #92)


Hello!

Can you attach one or both the apps so I can test.

Are they Win32 apps?

Did you export them recently or are they old exports?

Cheers!

**Comment by Nordstrom96** [comment]
I answered as a mail, Dunno if that ruined the answer here or am I good?

**Comment by Micke-K** [comment]
That didn't work :) 

But I had a look. It looks likes like Microsoft has changed how they set the minimum OS,
Property name and value is changed:

New setting:
"minimumSupportedWindowsRelease":  "2H20",

Old settings:
    "minimumSupportedOperatingSystem":  {
                                            "v8_0":  false,
                                            "v8_1":  false,
                                            "v10_0":  false,
                                            "v10_1607":  false,
                                            "v10_1703":  false,
                                            "v10_1709":  false,
                                            "v10_1803":  false,
                                            "v10_1809":  false,
                                            "v10_1903":  false,
                                            "v10_1909":  false,
                                            "v10_2004":  false,
                                            "v10_2H20":  true,
                                            "v10_21H1":  false
                                        },

I'll have a look if I can fix this in the code somehow

Cheers!

**Comment by Micke-K** [comment]
I did some test and all I need to do is to remove the minimumSupportedOperatingSystem.

Can you test with this version? Replace the existing EndpointManager.psm1 in the Extensions folder.

[EndpointManager.zip](https://github.com/Micke-K/IntuneManagement/files/9672761/EndpointManager.zip)

Cheers

**Comment by Nordstrom96** [comment]
Hello again,

This is what i get:
[cid:a2060459-f509-4874-a321-644d98694d8f]
Looks like the same sadly.
________________________________
Fra: Mikael Karlsson ***@***.***>
Sendt: torsdag 29. september 2022 10:44
Til: Micke-K/IntuneManagement ***@***.***>
Kopi: Nordstrom96 ***@***.***>; Author ***@***.***>
Emne: Re: [Micke-K/IntuneManagement] Problem loading Application .json files (Issue #92)


I did some test and all I need to do is to remove the minimumSupportedOperatingSystem.

Can you test with this version? Replace the existing EndpointManager.psm1 in the Extensions folder.

EndpointManager.zip<https://github.com/Micke-K/IntuneManagement/files/9672761/EndpointManager.zip>

Cheers

**Comment by Nordstrom96** [comment]
<img width="665" alt="asdasdasdasdasd" src="https://user-images.githubusercontent.com/96183263/192991281-1bd45dfe-1d52-43c7-a4c4-6e5f1725fbe6.png">

**Comment by Micke-K** [comment]
Was that with the new file?

**Comment by Nordstrom96** [comment]
Replaced the old file with the new yes.
________________________________
Fra: Mikael Karlsson ***@***.***>
Sendt: torsdag 29. september 2022 12:35
Til: Micke-K/IntuneManagement ***@***.***>
Kopi: Nordstrom96 ***@***.***>; Author ***@***.***>
Emne: Re: [Micke-K/IntuneManagement] Problem loading Application .json files (Issue #92)


Was that with the new file?

**Comment by Micke-K** [comment]
Hmmm that's not good since that helped me. 

I guess I need your json so I can test with what you have. 

Cheers!

**Comment by Nordstrom96** [comment]
[BizConfig - Office Apps (Teams).zip](https://github.com/Micke-K/IntuneManagement/files/9674485/BizConfig.-.Office.Apps.Teams.zip)

There you go!

**Comment by Micke-K** [comment]
Ah it was a Microsoft Apps that failed and not a Win32. I should have guessed that based on the name :) 

This is the problem. Your file has:
"officeSuiteAppDefaultFileFormat":  "notConfigured"
change that to:
"officeSuiteAppDefaultFileFormat":  "OfficeOpenDocumentFormat"

Try that and let me know if it works. I could import after changing that property.

Was the Edge app an actual Microsoft Edge app or a Win32? Can you send me that json as well?

Cheers!

**Comment by Micke-K** [comment]
Hello!

Try this script. This should fix the Microsoft Apps (BizConfig - Office Apps (Teams)) import. 

This will set the default format to officeOpenXMLFormat if is not configured.

I could NOT replicate the import issue with the Edge json. It was imported successfully without any changes.
Do you still have an issue with that?

Let me know how it goes!

Cheers!

[EndpointManager.zip](https://github.com/Micke-K/IntuneManagement/files/9689238/EndpointManager.zip)

**Comment by Nordstrom96** [comment]
Hello,

The Edge.json works without errors. Seems like Office still has the same problem sadly.

**Comment by Micke-K** [comment]
Hello!

That is weird. I have no problem importing your  'BizConfig - Office Apps (Teams).json' with this change
You should see the following information in the log:
WARNING: Changing officeSuiteAppDefaultFileFormat to OfficeOpenDocumentFormat

I haven't done anything for the Edge json so that should just have worked from the beginning.

Cheers!

**Comment by Nordstrom96** [comment]
![image](https://user-images.githubusercontent.com/96183263/193526481-1b39e230-0904-4937-b77e-42c1b11d7813.png)
This is the only log i can find.

**Comment by Micke-K** [comment]
If you go to File -> About. What version is EndpointManager?
And what does the lines 1924-1931 in EndpointManage.psm1 look like?

**Comment by Nordstrom96** [comment]
![image](https://user-images.githubusercontent.com/96183263/193542779-0613cc32-6219-4f19-8785-08610789ce17.png)
![image](https://user-images.githubusercontent.com/96183263/193543077-bf480a6a-accd-42db-ac65-41bda27b5220.png)

**Comment by Micke-K** [comment]
That is very annoying. I cannot explain why it works for me and not for you. 

One other test you can do is to creat a new app manually. Then export/import that app and see if it works. 

Cheers!

**Comment by Micke-K** [comment]
Can you try this version and send a screenshot of the log. 
I added some debug logging so the result should be the same, failing, but I want to check that it is actually setting the correct value.

Cheers

[EndpointManager.zip](https://github.com/Micke-K/IntuneManagement/files/9714311/EndpointManager.zip)

**Comment by Nordstrom96** [comment]
Hey again,

It looks like we've resolved the problem today by creating a new .json file for the Office+teams.
Looks like some values had changed for some reasons, so now it seems like it works.
Do you still want me to try this version?

**Comment by Micke-K** [comment]
Great! That is good news.

Only if you have time. 

It would be good to know what the difference is between the json files. If you could upload the new one or do a diff between them. 

Thank you for all the testing!

Cheers

**Comment by Nordstrom96** [comment]
For some reason it looks like the old .josn "worked" now aswell.
Here is the Printscreen:
![image](https://user-images.githubusercontent.com/96183263/194032719-1abaf193-ac70-4634-ba3a-2acece5ed1c8.png)

**Comment by Micke-K** [comment]
Well, that is even better :)

Can we close this now?

Cheers!

**Comment by Nordstrom96** [comment]
Yes we can! :) Thanks for the help.
