### ISSUE TITLE
Export/Import Application with intunewin

### ISSUE THREAD

**Issue by geby85** [Micke-K/IntuneManagement#93]
Hi,

I tried to export apps and import them to the same, or to another Tennant.
But the app always seems to be waiting for the intunewin in the background hat does not seem to be exported/imported with.

Am I doing wrong, or is my use case unusual?
Any idea how to upload the intunewin after importing just the json? Intune does net let me edit the imported app until it received the first intunewin I think.

Regards
Daniel

**Comment by Micke-K** [comment]
Hello!

It's not possible to export the .intunewin files so they are not a part of it. There are a few Discussions and closed Issues about it. In short, you can import with the .intunewin file if you put the on a folderand point the intune app packages setting to it. 

You can upload the .intunewin file manually for apps imported without the file. Go to the detailed view of the app. 

Cheers!

**Comment by Micke-K** [comment]
Closing this since it was answered previously. 

Let me know if you still have issues with it

Cheers!

**Comment by Micke-K** [comment]
You can specify the folder in Settings and then copy .intunewin files there.

![image](https://user-images.githubusercontent.com/43226266/197050888-2fa3ccb6-7640-4cd9-b98d-fe791d59f589.png)

If you have created an app without .intunewin files you can upload the file in the here:

![image](https://user-images.githubusercontent.com/43226266/197051289-ac7f6ed5-118b-4361-8c73-cc8a5a9837d1.png)

Cheers!
