### ISSUE TITLE
The term 'Invoke-WordTranslateColumnHeader' is not recognized as the name of a cmdlet, function, script file, or operable program

### ISSUE THREAD

**Issue by skippernl** [Micke-K/IntuneManagement#99]
Running documentation of a tennant and looking at the powershell console I can see this message on multiple applications.

Documentation is created. Looking at the powershell scripts I cannot find that function.

**Comment by Micke-K** [comment]
Hello,

Yes, that was removed since the function was duplicated. However, it is fixed. I have it included in the following link. I am writing a release but I have too much work at the moment. 

Let me know if you test it and thank you so much for reporting it!

Cheers!

[Extensions](https://github.com/Micke-K/IntuneManagement/files/9980915/Extensions.zip)

**Comment by skippernl** [comment]
Hi, Tried the new extentions
![image](https://user-images.githubusercontent.com/5336247/202195526-39a80fd5-0393-4aa1-aede-4d9c92bb0e68.png)
Bulk - Document Types is missing. I am using that to create the word document for documentation.

**Comment by Micke-K** [comment]
Did you delete all files in the Extension folder before copying? The zip file only included the updated modules. 

Cheers!

**Comment by grandslamjmh** [comment]
I would like to second this issue. I have not used any previous versions. Started with 3.7.3.1

I'm running PowerShell 7.3.1 when I noticed 'Invoke-WordTranslateColumnHeader' is not recognized. 
It doesn't seem to have the issue on some applications. but most are throwing.

**Comment by skippernl** [comment]
There's a private fix for this that is working.Micke could send it to you. Op 21 dec. 2022 16:23 schreef Jordan Hoff ***@***.***>:
I would like to second this issue. I have not used any previous versions. Started with 3.7.3.1
I'm running PowerShell 7.3.1 when I noticed 'Invoke-WordTranslateColumnHeader' is not recognized.
It doesn't seem to have the issue on some applications. but most are throwing.

**Comment by Micke-K** [comment]
Hello

This is fixed in 3.8.1

Let me now if you test it or if I can now close this issue

Cheers!

**Comment by skippernl** [comment]
Nice great work

Op do 26 jan. 2023 12:34 schreef Mikael Karlsson ***@***.***>:

**Comment by skippernl** [comment]
I have not seen this error in the lastest version. Thank you.

**Comment by Micke-K** [comment]
Issue fixed. Closing.

Cheers!
